---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-${DB_CONNECTION_NAME}
  labels:
    app: pgbouncer-${DB_CONNECTION_NAME}
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: pgbouncer-${DB_CONNECTION_NAME}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-tls
data:
  userlist.txt: |
  "admin" "md5f6fdffe48c908deb0f4c3bd36c032e72"
  BaltimoreCyberTrustRoot.crt.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDdzCCAl+gAwIBAgIEAgAAuTANBgkqhkiG9w0BAQUFADBaMQswCQYDVQQGEwJJ
    RTESMBAGA1UEChMJQmFsdGltb3JlMRMwEQYDVQQLEwpDeWJlclRydXN0MSIwIAYD
    VQQDExlCYWx0aW1vcmUgQ3liZXJUcnVzdCBSb290MB4XDTAwMDUxMjE4NDYwMFoX
    DTI1MDUxMjIzNTkwMFowWjELMAkGA1UEBhMCSUUxEjAQBgNVBAoTCUJhbHRpbW9y
    ZTETMBEGA1UECxMKQ3liZXJUcnVzdDEiMCAGA1UEAxMZQmFsdGltb3JlIEN5YmVy
    VHJ1c3QgUm9vdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKMEuyKr
    mD1X6CZymrV51Cni4eiVgLGw41uOKymaZN+hXe2wCQVt2yguzmKiYv60iNoS6zjr
    IZ3AQSsBUnuId9Mcj8e6uYi1agnnc+gRQKfRzMpijS3ljwumUNKoUMMo6vWrJYeK
    mpYcqWe4PwzV9/lSEy/CG9VwcPCPwBLKBsua4dnKM3p31vjsufFoREJIE9LAwqSu
    XmD+tqYF/LTdB1kC1FkYmGP1pWPgkAx9XbIGevOF6uvUA65ehD5f/xXtabz5OTZy
    dc93Uk3zyZAsuT3lySNTPx8kmCFcB5kpvcY67Oduhjprl3RjM71oGDHweI12v/ye
    jl0qhqdNkNwnGjkCAwEAAaNFMEMwHQYDVR0OBBYEFOWdWTCCR1jMrPoIVDaGezq1
    BE3wMBIGA1UdEwEB/wQIMAYBAf8CAQMwDgYDVR0PAQH/BAQDAgEGMA0GCSqGSIb3
    DQEBBQUAA4IBAQCFDF2O5G9RaEIFoN27TyclhAO992T9Ldcw46QQF+vaKSm2eT92
    9hkTI7gQCvlYpNRhcL0EYWoSihfVCr3FvDB81ukMJY2GQE/szKN+OMY3EU/t3Wgx
    jkzSswF07r51XgdIGn9w/xZchMB5hbgF/X++ZRGjD8ACtPhSNzkE1akxehi/oCr0
    Epn3o0WC4zxe9Z2etciefC7IpJ5OCBRLbf1wbWsaY71k5h+3zvDyny67G7fyUIhz
    ksLi4xaNmjICq44Y3ekQEe5+NauQrz4wlHrQMz2nZQ/1/I6eYs9HRCwBXbsdtTLS
    R9I4LtD+gdwyah617jzV/OeBHRnDJELqYzmp
    -----END CERTIFICATE-----
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer-${DB_CONNECTION_NAME}
  labels:
    app: pgbouncer-${DB_CONNECTION_NAME}
spec:
  selector:
    matchLabels:
      app: pgbouncer-${DB_CONNECTION_NAME}
  template:
    metadata:
      labels:
        app: pgbouncer-${DB_CONNECTION_NAME}
    spec:
      volumes:
      - name: config
        configMap:
          name: pgbouncer-tls
          items:
          - key: "BaltimoreCyberTrustRoot.crt.pem"
            path: "BaltimoreCyberTrustRoot.crt.pem"
          - key: "userlist.txt"
            path: "userlist.txt"
      containers:
        - name: pgbouncer
          image: pgbouncer/pgbouncer
          ports:
            - containerPort: 5432
          volumeMounts:
          - name: config
            mountPath: "/config"
            readOnly: true
          env:
            - name: DATABASES_HOST
              value: ${PGHOST}
            - name: DATABASES_PORT
              value: "5432"
            - name: DATABASES_USER
              value: ${PGUSER}
            - name: DATABASES_PASSWORD
              value: ${PGPASSWORD}
            - name: DATABASES_DBNAME
              value: emjpm_master
            - name: DATABASES_POOL_MODE
              value: session
            - name: PGBOUNCER_LISTEN_PORT
              value: "5432"
            - name: PGBOUNCER_IGNORE_STARTUP_PARAMETERS
              value: "extra_float_digits,options"
            - name: PGBOUNCER_ADMIN_USERS
              value: "admin"
            - name: PGBOUNCER_SERVER_TLS_SSLMODE
              value: "verify-full"
            - name: PGBOUNCER_SERVER_TLS_CA_FILE
              value: /config/BaltimoreCyberTrustRoot.crt.pem
            - name: PGBOUNCER_AUTH_FILE
              value: "/config/userlist.txt"
            - name: PGBOUNCER_TCP_KEEPALIVE
              value: "1"
            - name: PGBOUNCER_MIN_POOL_SIZE
              value: "2"
            - name: PGBOUNCER_POOL_MODE
              value: "session"
            # - name: PGBOUNCER_DEFAULT_POOL_SIZE
            # value: "2"
            # - name: PGBOUNCER_RESERVE_POOL_SIZE
            # value: "2"
            # - name: PGBOUNCER_AUTH_QUERY
            # value: "SELECT p_user, p_password FROM public.lookup($1)"
            # - name: PGBOUNCER_CLIENT_TLS_SSLMODE
            #   value: "disable"
            # - name: PGBOUNCER_TCP_KEEPALIVE
            #   value: "180"
