.k8s-deploy-postgres:
  extends: .base_docker_helm_image_stage
  script:
    - export POSTGRESQL_USER=$(kubectl get secret -n ${K8S_NAMESPACE} emjpm-secret -o jsonpath='{.data.POSTGRES_USER}' | base64 --decode)
    - export POSTGRESQL_PASSWORD=$(kubectl get secret -n ${K8S_NAMESPACE} emjpm-secret -o jsonpath='{.data.POSTGRES_PASSWORD}' | base64 --decode)

    - envsubst < ./.k8s/postgres/values-postgresql.yaml > ./values-postgresql.yaml
    - envsubst < ./.k8s/postgres/job-inject-dataset.yml > ./job-inject-dataset.yml
    #
    - helm init --client-only
    - helm upgrade --debug --install ${POSTGRES_HOST} --wait -f ./values-postgresql.yaml stable/postgresql --namespace ${K8S_NAMESPACE}
    #
    - kubectl delete job "${K8S_PROJECT}-dataset-${BRANCH_HASH}" -n ${K8S_NAMESPACE} || true;
    - cat ./.k8s/postgres/configmap.yml | envsubst | kubectl apply -n ${K8S_NAMESPACE} -f -
    - kubectl apply -f ./job-inject-dataset.yml -n ${K8S_NAMESPACE}
