.k8s-deploy-postgres-dev:
  extends: .base_docker_kube_image_stage
  script:
    - envsubst < ./.k8s/postgres/deployment.yml > ./deployment.yml
    - envsubst < ./.k8s/postgres/service.yml > ./service.yml
    #
    - kubectl apply -f ./.k8s/postgres/configmap.yml
    - kubectl apply -f ./deployment.yml
    - kubectl apply -f ./service.yml
    #
    - k8s/scripts/inject_data_postgres.sh $BRANCH_HASH

.k8s-deploy-postgres-prod:
  extends: .base_docker_kube_image_stage
  script:
    - envsubst < k8s/postgres/pod-inject-dataset-prod.yml > ./pod-inject-dataset.yml
    - envsubst < k8s/postgres/pod-init-postgres-prod.yml > ./pod-init-postgres.yml
    #
    - kubectl apply -f ./.k8s/postgres/configmap.yml
    - kubectl apply -f ./pod-init-postgres.yml
    - k8s/scripts/inject_data_postgres.sh
