.k8s-deploy-postgres-dev:
  extends: .base_docker_kube_image_stage
  script:
    - cat ./.k8s/postgres/cluster.yml | envsubst | kubectl apply -f -

.k8s-deploy-postgres-prod:
  extends: .base_docker_kube_image_stage
  script:
    - envsubst < ./.k8s/postgres/pod-inject-dataset-prod.yml > ./pod-inject-dataset.yml
    - envsubst < ./.k8s/postgres/pod-init-postgres-prod.yml > ./pod-init-postgres.yml
    #
    - kubectl apply -f ./.k8s/postgres/configmap.yml
    - kubectl apply -f ./pod-init-postgres.yml
    - sh ./.k8s/postgres/inject_data_postgres.sh $BRANCH_HASH
