.k8s-deploy-postgres:
  extends: .base_docker_helm_image_stage
  script:
    - export POSTGRESQL_USER=emjpm
    - export POSTGRESQL_PASSWORD=$(kubectl get secret emjpm-secret -o jsonpath='{.data.POSTGRES_EMJPM_PASSWORD}' | base64 --decode)
    #
    - envsubst < ./.k8s/postgres/values-postgresql.yaml > ./values-postgresql.yaml
    #
    - helm init --client-only
    - helm upgrade --install ${POSTGRES_HOST} --wait -f ./values-postgresql.yaml stable/postgresql --namespace ${K8S_NAMESPACE}
    #
    - kubectl delete configmap ${K8S_PROJECT}-dataset-configmap-${BRANCH_HASH} || true;
    - kubectl create configmap ${K8S_PROJECT}-dataset-configmap-${BRANCH_HASH} --from-file=./.k8s/postgres/configmap
    #
    - kubectl delete job ${K8S_PROJECT}-dataset-${BRANCH_HASH} || true;
    - cat ./.k8s/postgres/job-inject-dataset.yml | envsubst | kubectl apply -f -
