---
kind: Pod
apiVersion: v1
metadata:
  name: ${EMJPM_REGISTRY}-dataset-${BRANCH_HASH}
  labels:
    app: ${EMJPM_REGISTRY}-dataset
    branch: ${EMJPM_REGISTRY}-dataset-${BRANCH_HASH}
spec:
  containers:
    - image: ${EMJPM_REGISTRY}:${IMAGE_TAG}
      name: ${EMJPM_REGISTRY}-dataset-${BRANCH_HASH}
      command: ["sh"]
      args: ["/dataset/inject-dataset.sh"]
      env:
        - name: DATABASE_URL
          value: "psql://${POSTGRES_API_USER}:${POSTGRES_API_USER_PASSWORD}@{POSTGRES_HOST}/emjpm_dev"
        - name: NODE_ENV
          value: "development"
      volumeMounts:
        - name: dataset
          mountPath: /dataset
  volumes:
    - name: dataset
      configMap:
        name: init-postgres
  restartPolicy: Never
  initContainers:
    - name: wait-for-postgres
      image: postgres:11-alpine
      imagePullPolicy: Always
      command:
        - sh
        - -c
        - |
          retry=120; # 5s * (12 * 10) = 10min
          while ! pg_isready -h ${POSTGRES_HOST} > /dev/null 2> /dev/null && [[ $(( retry-- )) -gt 0 ]];
            do
              echo "Waiting for Postgres to go Green ($(( retry )))" ; sleep 5s ; done ;
          echo Ready;
