---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ${CERTIFICATE_NAME}
spec:
  secretName: ${CERTIFICATE_NAME}-secret
  dnsNames:
    - ${FRONTEND_HOST}
    - ${API_HOST}
    - ${HASURA_HOST}
    - ${METABASE_HOST}
  acme:
    config:
      - http01:
          ingressClass: azure/application-gateway
        domains:
          - ${FRONTEND_HOST}
          - ${API_HOST}
          - ${HASURA_HOST}
          - ${METABASE_HOST}
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
