version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
        environment:
          NODE_ENV: test

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test
          POSTGRES_DB: emjpm_test
        command: -p 5434
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
            - dependencies-
      - run:
          name: Install dependencies
          command: NODE_ENV=development npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Run tests
          command: npm test
