module.exports = {
  INIT_ENQUETE_REPONSE: `
    mutation create_enquete_individuel_reponse(
      $enqueteId: Int!,
      $departementCode: String,
      $mandataireId: Int!,
      
      $departement: String,
      $region: String,
      $raison_sociale: String,
      $personnalite_juridique_etablissement: String,
      $total_mesures_etablissements: Int,
      $nombre_lits_journee_hospitalisation: jsonb,
      $actions_information_tuteurs_familiaux: Boolean,
      $activite_exercee_par: String,
      $etablissements_type: String,

      $nb_preposes_mjpm: Int,
      $nb_preposes_mjpm_etp: Float,
      $formation_preposes_mjpm: jsonb,
      $niveaux_qualification: jsonb,
      $nb_preposes_homme: Int,
      $nb_preposes_femme: Int,
      $nb_autre_personnel: Int,
      $nb_autre_personnel_etp: Float,

      $curatelle_renforcee_etablissement_debut_annee: Int,
      $curatelle_renforcee_etablissement_fin_annee: Int,
      $curatelle_renforcee_domicile_debut_annee: Int,
      $curatelle_renforcee_domicile_fin_annee: Int,
      $curatelle_simple_etablissement_debut_annee: Int,
      $curatelle_simple_etablissement_fin_annee: Int,
      $curatelle_simple_domicile_debut_annee: Int,
      $curatelle_simple_domicile_fin_annee: Int,
      $tutelle_etablissement_debut_annee: Int,
      $tutelle_etablissement_fin_annee: Int,
      $tutelle_domicile_debut_annee: Int,
      $tutelle_domicile_fin_annee: Int,
      $accompagnement_judiciaire_etablissement_debut_annee: Int,
      $accompagnement_judiciaire_etablissement_fin_annee: Int,
      $accompagnement_judiciaire_domicile_debut_annee: Int,
      $accompagnement_judiciaire_domicile_fin_annee: Int,
      $curatelle_biens_etablissement_debut_annee: Int,
      $curatelle_biens_etablissement_fin_annee: Int,
      $curatelle_biens_domicile_debut_annee: Int,
      $curatelle_personne_etablissement_debut_annee: Int,
      $curatelle_personne_etablissement_fin_annee: Int,
      $curatelle_personne_domicile_debut_annee: Int,
      $curatelle_personne_domicile_fin_annee: Int,
      $subroge_tuteur_createur_debut_annee: Int,
      $subroge_tuteur_createur_fin_annee: Int,
      $sauvegarde_justice_debut_annee: Int,
      $sauvegarde_justice_fin_annee: Int,
      $mandat_adhoc_majeur_debut_annee: Int,
      $mandat_adhoc_majeur_fin_annee: Int,
      $curatelle_renforcee_etablissement_mesures_nouvelles: Int,
      $curatelle_renforcee_etablissement_sortie_mesures: Int,
      $curatelle_renforcee_domicile_mesures_nouvelles: Int,
      $curatelle_renforcee_domicile_sortie_mesures: Int,
      $curatelle_simple_etablissement_mesures_nouvelles: Int,
      $curatelle_simple_etablissement_sortie_mesures: Int,
      $curatelle_simple_domicile_mesures_nouvelles: Int,
      $curatelle_simple_domicile_sortie_mesures: Int,
      $tutelle_etablissement_mesures_nouvelles: Int,
      $tutelle_etablissement_sortie_mesures: Int,
      $tutelle_domicile_mesures_nouvelles: Int,
      $tutelle_domicile_sortie_mesures: Int,
      $accompagnement_judiciaire_etablissement_mesures_nouvelles: Int,
      $accompagnement_judiciaire_etablissement_sortie_mesures: Int,
      $accompagnement_judiciaire_domicile_mesures_nouvelles: Int,
      $accompagnement_judiciaire_domicile_sortie_mesures: Int,
      $curatelle_biens_etablissement_mesures_nouvelles: Int,
      $curatelle_biens_etablissement_sortie_mesures: Int,
      $curatelle_biens_domicile_mesures_nouvelles: Int,
      $curatelle_biens_domicile_sortie_mesures: Int,
      $curatelle_personne_etablissement_mesures_nouvelles: Int,
      $curatelle_personne_etablissement_sortie_mesures: Int,
      $curatelle_personne_domicile_mesures_nouvelles: Int,
      $curatelle_personne_domicile_sortie_mesures: Int,
      $subroge_tuteur_createur_mesures_nouvelles: Int,
      $subroge_tuteur_createur_sortie_mesures: Int,
      $sauvegarde_justice_mesures_nouvelles: Int,
      $sauvegarde_justice_sortie_mesures: Int,
      $mandat_adhoc_majeur_mesures_nouvelles: Int,
      $mandat_adhoc_majeur_sortie_mesures: Int,
      $revisions_main_levee: Int,
      $revisions_masp: Int,
      $revisions_reconduction: Int,
      $revisions_changement: Int,
      $revisions_autre: Int,
      $sorties_main_levee: Int,
      $sorties_deces: Int,
      $sorties_masp: Int,

      $tutelle_age_inf_25_ans_homme: Int,
      $tutelle_age_inf_25_ans_femme: Int,
      $tutelle_age_25_39_ans_homme: Int,
      $tutelle_age_25_39_ans_femme: Int,
      $tutelle_age_40_59_ans_homme: Int,
      $tutelle_age_40_59_ans_femme: Int,
      $tutelle_age_60_74_ans_homme: Int,
      $tutelle_age_60_74_ans_femme: Int,
      $tutelle_age_sup_75_ans_homme: Int,
      $tutelle_age_sup_75_ans_femme: Int,
      $curatelle_age_inf_25_ans_homme: Int,
      $curatelle_age_inf_25_ans_femme: Int,
      $curatelle_age_25_39_ans_homme: Int,
      $curatelle_age_25_39_ans_femme: Int,
      $curatelle_age_40_59_ans_homme: Int,
      $curatelle_age_40_59_ans_femme: Int,
      $curatelle_age_60_74_ans_homme: Int,
      $curatelle_age_60_74_ans_femme: Int,
      $curatelle_age_sup_75_ans_homme: Int,
      $curatelle_age_sup_75_ans_femme: Int,
      $maj_age_inf_25_ans_homme: Int,
      $maj_age_inf_25_ans_femme: Int,
      $maj_age_25_39_ans_homme: Int,
      $maj_age_25_39_ans_femme: Int,
      $maj_age_40_59_ans_homme: Int,
      $maj_age_40_59_ans_femme: Int,
      $maj_age_60_74_ans_homme: Int,
      $maj_age_60_74_ans_femme: Int,
      $maj_age_sup_75_ans_homme: Int,
      $maj_age_sup_75_ans_femme: Int,
      $sauvegarde_justice_age_inf_25_ans_homme: Int,
      $sauvegarde_justice_age_inf_25_ans_femme: Int,
      $sauvegarde_justice_age_25_39_ans_homme: Int,
      $sauvegarde_justice_age_25_39_ans_femme: Int,
      $sauvegarde_justice_age_40_59_ans_homme: Int,
      $sauvegarde_justice_age_40_59_ans_femme: Int,
      $sauvegarde_justice_age_60_74_ans_homme: Int,
      $sauvegarde_justice_age_60_74_ans_femme: Int,
      $sauvegarde_justice_age_sup_75_ans_homme: Int,
      $sauvegarde_justice_age_sup_75_ans_femme: Int,
      $autre_mesures_age_inf_25_ans_homme: Int,
      $autre_mesures_age_inf_25_ans_femme: Int,
      $autre_mesures_age_25_39_ans_homme: Int,
      $autre_mesures_age_25_39_ans_femme: Int,
      $autre_mesures_age_40_59_ans_homme: Int,
      $autre_mesures_age_40_59_ans_femme: Int,
      $autre_mesures_age_60_74_ans_homme: Int,
      $autre_mesures_age_60_74_ans_femme: Int,
      $autre_mesures_age_sup_75_ans_homme: Int,
      $autre_mesures_age_sup_75_ans_femme: Int,
      $tutelle_anciennete_inf_1_an: Int,
      $tutelle_anciennete_1_3_ans: Int,
      $tutelle_anciennete_3_5_ans: Int,
      $tutelle_anciennete_5_10_ans: Int,
      $tutelle_anciennete_sup_10_ans: Int,
      $curatelle_anciennete_inf_1_an: Int,
      $curatelle_anciennete_1_3_ans: Int,
      $curatelle_anciennete_3_5_ans: Int,
      $curatelle_anciennete_5_10_ans: Int,
      $curatelle_anciennete_sup_10_ans: Int,
      $maj_anciennete_inf_1_an: Int,
      $maj_anciennete_1_3_ans: Int,
      $maj_anciennete_3_5_ans: Int,
      $maj_anciennete_5_10_ans: Int,
      $maj_anciennete_sup_10_ans: Int,
      $sauvegarde_justice_anciennete_inf_1_an: Int,
      $sauvegarde_justice_anciennete_1_3_ans: Int,
      $sauvegarde_justice_anciennete_3_5_ans: Int,
      $sauvegarde_justice_anciennete_5_10_ans: Int,
      $sauvegarde_justice_anciennete_sup_10_ans: Int,
      $autre_mesures_anciennete_inf_1_an: Int,
      $autre_mesures_anciennete_1_3_ans: Int,
      $autre_mesures_anciennete_3_5_ans: Int,
      $autre_mesures_anciennete_5_10_ans: Int,
      $autre_mesures_anciennete_sup_10_ans: Int,
      $tutelle_etablissement_personne_handicapee: Int,
      $tutelle_service_personne_handicapee: Int,
      $tutelle_ehpad: Int,
      $tutelle_autre_etablissement_personne_agee: Int,
      $tutelle_chrs: Int,
      $tutelle_service_hospitalier_soins_longue_duree: Int,
      $tutelle_service_psychiatrique: Int,
      $tutelle_autre_service: Int,
      $curatelle_etablissement_personne_handicapee: Int,
      $curatelle_service_personne_handicapee: Int,
      $curatelle_ehpad: Int,
      $curatelle_autre_etablissement_personne_agee: Int,
      $curatelle_chrs: Int,
      $curatelle_service_hospitalier_soins_longue_duree: Int,
      $curatelle_service_psychiatrique: Int,
      $curatelle_autre_service: Int,
      $maj_etablissement_personne_handicapee: Int,
      $maj_service_personne_handicapee: Int,
      $maj_ehpad: Int,
      $maj_autre_etablissement_personne_agee: Int,
      $maj_chrs: Int,
      $maj_service_hospitalier_soins_longue_duree: Int,
      $maj_service_psychiatrique: Int,
      $maj_autre_service: Int,
      $sauvegarde_justice_etablissement_personne_handicapee: Int,
      $sauvegarde_justice_service_personne_handicapee: Int,
      $sauvegarde_justice_ehpad: Int,
      $sauvegarde_justice_autre_etablissement_personne_agee: Int,
      $sauvegarde_justice_chrs: Int,
      $sauvegarde_justice_service_hospitalier_soins_longue_duree: Int,
      $sauvegarde_justice_service_psychiatrique: Int,
      $sauvegarde_justice_autre_service: Int,
      $autre_mesures_etablissement_personne_handicapee: Int,
      $autre_mesures_service_personne_handicapee: Int,
      $autre_mesures_ehpad: Int,
      $autre_mesures_autre_etablissement_personne_agee: Int,
      $autre_mesures_chrs: Int,
      $autre_mesures_service_hospitalier_soins_longue_duree: Int,
      $autre_mesures_service_psychiatrique: Int,
      $autre_mesures_autre_service: Int,
    ) {
      insert_enquete_reponses
        (objects: [
          {
            enquete_id: $enqueteId,
            departement_code: $departementCode,
            user_type: "prepose",
            mandataire_id: $mandataireId,
            enquete_reponses_prepose_prestations_sociales: {data: [{

            }]},
            enquete_reponses_activites: {data: [{
              curatelle_renforcee_etablissement_debut_annee: $curatelle_renforcee_etablissement_debut_annee,
              curatelle_renforcee_etablissement_fin_annee: $curatelle_renforcee_etablissement_fin_annee,
              curatelle_renforcee_domicile_debut_annee: $curatelle_renforcee_domicile_debut_annee,
              curatelle_renforcee_domicile_fin_annee: $curatelle_renforcee_domicile_fin_annee,
              curatelle_simple_etablissement_debut_annee: $curatelle_simple_etablissement_debut_annee,
              curatelle_simple_etablissement_fin_annee: $curatelle_simple_etablissement_fin_annee,
              curatelle_simple_domicile_debut_annee: $curatelle_simple_domicile_debut_annee,
              curatelle_simple_domicile_fin_annee: $curatelle_simple_domicile_fin_annee,
              tutelle_etablissement_debut_annee: $tutelle_etablissement_debut_annee,
              tutelle_etablissement_fin_annee: $tutelle_etablissement_fin_annee,
              tutelle_domicile_debut_annee: $tutelle_domicile_debut_annee,
              tutelle_domicile_fin_annee: $tutelle_domicile_fin_annee,
              accompagnement_judiciaire_etablissement_debut_annee: $accompagnement_judiciaire_etablissement_debut_annee,
              accompagnement_judiciaire_etablissement_fin_annee: $accompagnement_judiciaire_etablissement_fin_annee,
              accompagnement_judiciaire_domicile_debut_annee: $accompagnement_judiciaire_domicile_debut_annee,
              accompagnement_judiciaire_domicile_fin_annee: $accompagnement_judiciaire_domicile_fin_annee,
              curatelle_biens_etablissement_debut_annee: $curatelle_biens_etablissement_debut_annee,
              curatelle_biens_etablissement_fin_annee: $curatelle_biens_etablissement_fin_annee,
              curatelle_biens_domicile_debut_annee: $curatelle_biens_domicile_debut_annee,
              curatelle_personne_etablissement_debut_annee: $curatelle_personne_etablissement_debut_annee,
              curatelle_personne_etablissement_fin_annee: $curatelle_personne_etablissement_fin_annee,
              curatelle_personne_domicile_debut_annee: $curatelle_personne_domicile_debut_annee,
              curatelle_personne_domicile_fin_annee: $curatelle_personne_domicile_fin_annee,
              subroge_tuteur_createur_debut_annee: $subroge_tuteur_createur_debut_annee,
              subroge_tuteur_createur_fin_annee: $subroge_tuteur_createur_fin_annee,
              sauvegarde_justice_debut_annee: $sauvegarde_justice_debut_annee,
              sauvegarde_justice_fin_annee: $sauvegarde_justice_fin_annee,
              mandat_adhoc_majeur_debut_annee: $mandat_adhoc_majeur_debut_annee,
              mandat_adhoc_majeur_fin_annee: $mandat_adhoc_majeur_fin_annee,
              curatelle_renforcee_etablissement_mesures_nouvelles: $curatelle_renforcee_etablissement_mesures_nouvelles,
              curatelle_renforcee_etablissement_sortie_mesures: $curatelle_renforcee_etablissement_sortie_mesures,
              curatelle_renforcee_domicile_mesures_nouvelles: $curatelle_renforcee_domicile_mesures_nouvelles,
              curatelle_renforcee_domicile_sortie_mesures: $curatelle_renforcee_domicile_sortie_mesures,
              curatelle_simple_etablissement_mesures_nouvelles: $curatelle_simple_etablissement_mesures_nouvelles,
              curatelle_simple_etablissement_sortie_mesures: $curatelle_simple_etablissement_sortie_mesures,
              curatelle_simple_domicile_mesures_nouvelles: $curatelle_simple_domicile_mesures_nouvelles,
              curatelle_simple_domicile_sortie_mesures: $curatelle_simple_domicile_sortie_mesures,
              tutelle_etablissement_mesures_nouvelles: $tutelle_etablissement_mesures_nouvelles,
              tutelle_etablissement_sortie_mesures: $tutelle_etablissement_sortie_mesures,
              tutelle_domicile_mesures_nouvelles: $tutelle_domicile_mesures_nouvelles,
              tutelle_domicile_sortie_mesures: $tutelle_domicile_sortie_mesures,
              accompagnement_judiciaire_etablissement_mesures_nouvelles: $accompagnement_judiciaire_etablissement_mesures_nouvelles,
              accompagnement_judiciaire_etablissement_sortie_mesures: $accompagnement_judiciaire_etablissement_sortie_mesures,
              accompagnement_judiciaire_domicile_mesures_nouvelles: $accompagnement_judiciaire_domicile_mesures_nouvelles,
              accompagnement_judiciaire_domicile_sortie_mesures: $accompagnement_judiciaire_domicile_sortie_mesures,
              curatelle_biens_etablissement_mesures_nouvelles: $curatelle_biens_etablissement_mesures_nouvelles,
              curatelle_biens_etablissement_sortie_mesures: $curatelle_biens_etablissement_sortie_mesures,
              curatelle_biens_domicile_mesures_nouvelles: $curatelle_biens_domicile_mesures_nouvelles,
              curatelle_biens_domicile_sortie_mesures: $curatelle_biens_domicile_sortie_mesures,
              curatelle_personne_etablissement_mesures_nouvelles: $curatelle_personne_etablissement_mesures_nouvelles,
              curatelle_personne_etablissement_sortie_mesures: $curatelle_personne_etablissement_sortie_mesures,
              curatelle_personne_domicile_mesures_nouvelles: $curatelle_personne_domicile_mesures_nouvelles,
              curatelle_personne_domicile_sortie_mesures: $curatelle_personne_domicile_sortie_mesures,
              subroge_tuteur_createur_mesures_nouvelles: $subroge_tuteur_createur_mesures_nouvelles,
              subroge_tuteur_createur_sortie_mesures: $subroge_tuteur_createur_sortie_mesures,
              sauvegarde_justice_mesures_nouvelles: $sauvegarde_justice_mesures_nouvelles,
              sauvegarde_justice_sortie_mesures: $sauvegarde_justice_sortie_mesures,
              mandat_adhoc_majeur_mesures_nouvelles: $mandat_adhoc_majeur_mesures_nouvelles,
              mandat_adhoc_majeur_sortie_mesures: $mandat_adhoc_majeur_sortie_mesures,
              revisions_main_levee: $revisions_main_levee,
              revisions_masp: $revisions_masp,
              revisions_reconduction: $revisions_reconduction,
              revisions_changement: $revisions_changement,
              revisions_autre: $revisions_autre,
              sorties_main_levee: $sorties_main_levee,
              sorties_deces: $sorties_deces,
              sorties_masp: $sorties_masp,
            }]},
            enquete_reponses_financements: {data: [{

            }]},
            enquete_reponses_modalites_exercices: {data: [{
              departement: $departement,
              region: $region,
              raison_sociale: $raison_sociale,
              personnalite_juridique_etablissement: $personnalite_juridique_etablissement,
              total_mesures_etablissements: $total_mesures_etablissements,
              nombre_lits_journee_hospitalisation: $nombre_lits_journee_hospitalisation,
              actions_information_tuteurs_familiaux: $actions_information_tuteurs_familiaux,
              activite_exercee_par: $activite_exercee_par,
              etablissements_type: $etablissements_type,
            }]},
            enquete_reponses_populations: {data: [{
              tutelle_age_inf_25_ans_homme: $tutelle_age_inf_25_ans_homme,
              tutelle_age_inf_25_ans_femme: $tutelle_age_inf_25_ans_femme,
              tutelle_age_25_39_ans_homme: $tutelle_age_25_39_ans_homme,
              tutelle_age_25_39_ans_femme: $tutelle_age_25_39_ans_femme,
              tutelle_age_40_59_ans_homme: $tutelle_age_40_59_ans_homme,
              tutelle_age_40_59_ans_femme: $tutelle_age_40_59_ans_femme,
              tutelle_age_60_74_ans_homme: $tutelle_age_60_74_ans_homme,
              tutelle_age_60_74_ans_femme: $tutelle_age_60_74_ans_femme,
              tutelle_age_sup_75_ans_homme: $tutelle_age_sup_75_ans_homme,
              tutelle_age_sup_75_ans_femme: $tutelle_age_sup_75_ans_femme,
              curatelle_age_inf_25_ans_homme: $curatelle_age_inf_25_ans_homme,
              curatelle_age_inf_25_ans_femme: $curatelle_age_inf_25_ans_femme,
              curatelle_age_25_39_ans_homme: $curatelle_age_25_39_ans_homme,
              curatelle_age_25_39_ans_femme: $curatelle_age_25_39_ans_femme,
              curatelle_age_40_59_ans_homme: $curatelle_age_40_59_ans_homme,
              curatelle_age_40_59_ans_femme: $curatelle_age_40_59_ans_femme,
              curatelle_age_60_74_ans_homme: $curatelle_age_60_74_ans_homme,
              curatelle_age_60_74_ans_femme: $curatelle_age_60_74_ans_femme,
              curatelle_age_sup_75_ans_homme: $curatelle_age_sup_75_ans_homme,
              curatelle_age_sup_75_ans_femme: $curatelle_age_sup_75_ans_femme,
              maj_age_inf_25_ans_homme: $maj_age_inf_25_ans_homme,
              maj_age_inf_25_ans_femme: $maj_age_inf_25_ans_femme,
              maj_age_25_39_ans_homme: $maj_age_25_39_ans_homme,
              maj_age_25_39_ans_femme: $maj_age_25_39_ans_femme,
              maj_age_40_59_ans_homme: $maj_age_40_59_ans_homme,
              maj_age_40_59_ans_femme: $maj_age_40_59_ans_femme,
              maj_age_60_74_ans_homme: $maj_age_60_74_ans_homme,
              maj_age_60_74_ans_femme: $maj_age_60_74_ans_femme,
              maj_age_sup_75_ans_homme: $maj_age_sup_75_ans_homme,
              maj_age_sup_75_ans_femme: $maj_age_sup_75_ans_femme,
              sauvegarde_justice_age_inf_25_ans_homme: $sauvegarde_justice_age_inf_25_ans_homme,
              sauvegarde_justice_age_inf_25_ans_femme: $sauvegarde_justice_age_inf_25_ans_femme,
              sauvegarde_justice_age_25_39_ans_homme: $sauvegarde_justice_age_25_39_ans_homme,
              sauvegarde_justice_age_25_39_ans_femme: $sauvegarde_justice_age_25_39_ans_femme,
              sauvegarde_justice_age_40_59_ans_homme: $sauvegarde_justice_age_40_59_ans_homme,
              sauvegarde_justice_age_40_59_ans_femme: $sauvegarde_justice_age_40_59_ans_femme,
              sauvegarde_justice_age_60_74_ans_homme: $sauvegarde_justice_age_60_74_ans_homme,
              sauvegarde_justice_age_60_74_ans_femme: $sauvegarde_justice_age_60_74_ans_femme,
              sauvegarde_justice_age_sup_75_ans_homme: $sauvegarde_justice_age_sup_75_ans_homme,
              sauvegarde_justice_age_sup_75_ans_femme: $sauvegarde_justice_age_sup_75_ans_femme,
              autre_mesures_age_inf_25_ans_homme: $autre_mesures_age_inf_25_ans_homme,
              autre_mesures_age_inf_25_ans_femme: $autre_mesures_age_inf_25_ans_femme,
              autre_mesures_age_25_39_ans_homme: $autre_mesures_age_25_39_ans_homme,
              autre_mesures_age_25_39_ans_femme: $autre_mesures_age_25_39_ans_femme,
              autre_mesures_age_40_59_ans_homme: $autre_mesures_age_40_59_ans_homme,
              autre_mesures_age_40_59_ans_femme: $autre_mesures_age_40_59_ans_femme,
              autre_mesures_age_60_74_ans_homme: $autre_mesures_age_60_74_ans_homme,
              autre_mesures_age_60_74_ans_femme: $autre_mesures_age_60_74_ans_femme,
              autre_mesures_age_sup_75_ans_homme: $autre_mesures_age_sup_75_ans_homme,
              autre_mesures_age_sup_75_ans_femme: $autre_mesures_age_sup_75_ans_femme,
              tutelle_anciennete_inf_1_an: $tutelle_anciennete_inf_1_an,
              tutelle_anciennete_1_3_ans: $tutelle_anciennete_1_3_ans,
              tutelle_anciennete_3_5_ans: $tutelle_anciennete_3_5_ans,
              tutelle_anciennete_5_10_ans: $tutelle_anciennete_5_10_ans,
              tutelle_anciennete_sup_10_ans: $tutelle_anciennete_sup_10_ans,
              curatelle_anciennete_inf_1_an: $curatelle_anciennete_inf_1_an,
              curatelle_anciennete_1_3_ans: $curatelle_anciennete_1_3_ans,
              curatelle_anciennete_3_5_ans: $curatelle_anciennete_3_5_ans,
              curatelle_anciennete_5_10_ans: $curatelle_anciennete_5_10_ans,
              curatelle_anciennete_sup_10_ans: $curatelle_anciennete_sup_10_ans,
              maj_anciennete_inf_1_an: $maj_anciennete_inf_1_an,
              maj_anciennete_1_3_ans: $maj_anciennete_1_3_ans,
              maj_anciennete_3_5_ans: $maj_anciennete_3_5_ans,
              maj_anciennete_5_10_ans: $maj_anciennete_5_10_ans,
              maj_anciennete_sup_10_ans: $maj_anciennete_sup_10_ans,
              sauvegarde_justice_anciennete_inf_1_an: $sauvegarde_justice_anciennete_inf_1_an,
              sauvegarde_justice_anciennete_1_3_ans: $sauvegarde_justice_anciennete_1_3_ans,
              sauvegarde_justice_anciennete_3_5_ans: $sauvegarde_justice_anciennete_3_5_ans,
              sauvegarde_justice_anciennete_5_10_ans: $sauvegarde_justice_anciennete_5_10_ans,
              sauvegarde_justice_anciennete_sup_10_ans: $sauvegarde_justice_anciennete_sup_10_ans,
              autre_mesures_anciennete_inf_1_an: $autre_mesures_anciennete_inf_1_an,
              autre_mesures_anciennete_1_3_ans: $autre_mesures_anciennete_1_3_ans,
              autre_mesures_anciennete_3_5_ans: $autre_mesures_anciennete_3_5_ans,
              autre_mesures_anciennete_5_10_ans: $autre_mesures_anciennete_5_10_ans,
              autre_mesures_anciennete_sup_10_ans: $autre_mesures_anciennete_sup_10_ans,
              tutelle_etablissement_personne_handicapee: $tutelle_etablissement_personne_handicapee,
              tutelle_service_personne_handicapee: $tutelle_service_personne_handicapee,
              tutelle_ehpad: $tutelle_ehpad,
              tutelle_autre_etablissement_personne_agee: $tutelle_autre_etablissement_personne_agee,
              tutelle_chrs: $tutelle_chrs,
              tutelle_service_hospitalier_soins_longue_duree: $tutelle_service_hospitalier_soins_longue_duree,
              tutelle_service_psychiatrique: $tutelle_service_psychiatrique,
              tutelle_autre_service: $tutelle_autre_service,
              curatelle_etablissement_personne_handicapee: $curatelle_etablissement_personne_handicapee,
              curatelle_service_personne_handicapee: $curatelle_service_personne_handicapee,
              curatelle_ehpad: $curatelle_ehpad,
              curatelle_autre_etablissement_personne_agee: $curatelle_autre_etablissement_personne_agee,
              curatelle_chrs: $curatelle_chrs,
              curatelle_service_hospitalier_soins_longue_duree: $curatelle_service_hospitalier_soins_longue_duree,
              curatelle_service_psychiatrique: $curatelle_service_psychiatrique,
              curatelle_autre_service: $curatelle_autre_service,
              maj_etablissement_personne_handicapee: $maj_etablissement_personne_handicapee,
              maj_service_personne_handicapee: $maj_service_personne_handicapee,
              maj_ehpad: $maj_ehpad,
              maj_autre_etablissement_personne_agee: $maj_autre_etablissement_personne_agee,
              maj_chrs: $maj_chrs,
              maj_service_hospitalier_soins_longue_duree: $maj_service_hospitalier_soins_longue_duree,
              maj_service_psychiatrique: $maj_service_psychiatrique,
              maj_autre_service: $maj_autre_service,
              sauvegarde_justice_etablissement_personne_handicapee: $sauvegarde_justice_etablissement_personne_handicapee,
              sauvegarde_justice_service_personne_handicapee: $sauvegarde_justice_service_personne_handicapee,
              sauvegarde_justice_ehpad: $sauvegarde_justice_ehpad,
              sauvegarde_justice_autre_etablissement_personne_agee: $sauvegarde_justice_autre_etablissement_personne_agee,
              sauvegarde_justice_chrs: $sauvegarde_justice_chrs,
              sauvegarde_justice_service_hospitalier_soins_longue_duree: $sauvegarde_justice_service_hospitalier_soins_longue_duree,
              sauvegarde_justice_service_psychiatrique: $sauvegarde_justice_service_psychiatrique,
              sauvegarde_justice_autre_service: $sauvegarde_justice_autre_service,
              autre_mesures_etablissement_personne_handicapee: $autre_mesures_etablissement_personne_handicapee,
              autre_mesures_service_personne_handicapee: $autre_mesures_service_personne_handicapee,
              autre_mesures_ehpad: $autre_mesures_ehpad,
              autre_mesures_autre_etablissement_personne_agee: $autre_mesures_autre_etablissement_personne_agee,
              autre_mesures_chrs: $autre_mesures_chrs,
              autre_mesures_service_hospitalier_soins_longue_duree: $autre_mesures_service_hospitalier_soins_longue_duree,
              autre_mesures_service_psychiatrique: $autre_mesures_service_psychiatrique,
              autre_mesures_autre_service: $autre_mesures_autre_service,
            }]},
            enquete_reponses_prepose_personel_formations: {data: [{
              nb_preposes_mjpm: $nb_preposes_mjpm,
              nb_preposes_mjpm_etp: $nb_preposes_mjpm_etp,
              formation_preposes_mjpm: $formation_preposes_mjpm,
              niveaux_qualification: $niveaux_qualification,
              nb_preposes_homme: $nb_preposes_homme,
              nb_preposes_femme: $nb_preposes_femme,
              nb_autre_personnel: $nb_autre_personnel,
              nb_autre_personnel_etp: $nb_autre_personnel_etp,
            }]}
          }
        ]){
          returning {
            id
            departement_code
            user_type
            mandataire_id
            service_id
            status
            submitted_at
            created_at
            enquete_id
          }
        }
    }
  `,
  SUBMIT_ENQUETE_REPONSE: `
  mutation submit_enquete_reponse($id: Int!, $submittedAt: timestamptz!) {
    update_enquete_reponses_by_pk(pk_columns: {id: $id}, _set: {submitted_at: $submittedAt, status: "submitted"}) {
      id
      departement_code
      mandataire_id
      service_id
      status
      submitted_at
      created_at
      enquete_id
    }
  }
  `,
};
