---
apiVersion: v1
kind: Secret
metadata:
  name: ${K8S_PROJECT}-azure-storage-${BRANCH_HASH}
type: Opaque
data:
  azurestorageaccountname: ${AZURE_STORAGE_ACCOUNT_NAME}
  azurestorageaccountkey: ${AZURE_STORAGE_ACCOUNT_KEY}
