---
apiVersion: v1
kind: Secret
metadata:
  name: ${AZURE_VOLUME_SECRET_NAME}
type: Opaque
data:
  azurestorageaccountname: ${AZURE_STORAGE_ACCOUNT_NAME}
  azurestorageaccountkey: ${AZURE_STORAGE_ACCOUNT_KEY}
