apiVersion: v1
kind: Secret
metadata:
  name: emjpm-secret
  namespace: ${K8S_NAMESPACE}
data:
  HASURA_GRAPHQL_ADMIN_SECRET: YWRtaW4= # admin
  SMTP_HOST: c210cC5tYWlsdHJhcC5pbw== # smtp.mailtrap.io
  SMTP_PORT: NTg3Cg== # 587
  SMTP_USER: Y2ZiZjk1MTk1N2M1NTk= # cfbf951957c559
  SMTP_PASS: ZjQyNjg0YmMzM2ViYmQ= # f42684bc33ebbd
  SMTP_FROM: Y29udGFjdEBlbWpwbS5mcg== # contact@emjpm.fr
  SENTRY_PUBLIC_DSN: aHR0cHM6Ly9kOWJhOWI3NWZmNzg0Y2JhODdhYmQ4NDdiNjE2MmIwMjplNzFkZWE1ZjFkZTI0ODU2ODM0NzBkYzZlZjRkZDJjZkBzZW50cnkuZmFicmlxdWUuc29jaWFsLmdvdXYuZnIvMw== # https://d9ba9b75ff784cba87abd847b6162b02:e71dea5f1de2485683470dc6ef4dd2cf@sentry.fabrique.social.gouv.fr/3
  HASURA_WEB_HOOK_SECRET: aGFzdXJhc2VjcmV0ZW1qcG0=
  AZURE_ACCOUNT_NAME: QVpVUkVfQUNDT1VOVF9OQU1F #AZURE_ACCOUNT_NAME
  AZURE_ACCOUNT_KEY: QVpVUkVfQUNDT1VOVF9LRVk= #AZURE_ACCOUNT_KEY
  OCMI_FILE_PASSWORD: T0NNSV9GSUxFX1BBU1NXT1JE #OCMI_FILE_PASSWORD
  OCMI_SYNC_FILE_ENABLED: ZmFsc2U= #false
  AUTH_PUBLIC_KEY: |
    LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FR
    OEFNSUlCQ2dLQ0FRRUF4SEczSlJ5MDFNTUdDbDFLeGh5SQo2c3FmOWZIMHBGTlN3ZVRZVk5UbTJY
    S0I3MjM5SU8xOHlYaDE1eTY5L2NwQ3RIRmtnQkFSSjlwcjN4QlNEcEYxClJRZlFTV1c5QnlmZHpP
    QS9rWlBKTWlFKy8raE81cTYvR25lMVJKZ0V4RTJGdUFhOHJqZnNmdFFQQk5zVVV6UHIKZC9tUWtK
    eGxYaDFVVWdoVmY5N0x1MEhhUi9ncmViazlxZzA3M1d5eDRqb3dURmh6OG9BWFpaa29lVHNxbTZQ
    dgpaZENQRW1ia0Q4djVwaDdxazBLcndTc1BuN1ZaalprRWFCcHRWWlEvYzROZGZ6Z3BDZ3pwMHRs
    M0lFa0ZDaUVECktkUlRhTzR2emhxODhUZmU0TVdSaDBDY1h3TE8rTXgzNkFXMEVhTnlzWTVRak9B
    NmozYThlbjZKQ2FkR1BWSTMKY1FJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
  AUTH_PRIVATE_KEY: |
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBeEhHM0pSeTAx
    TU1HQ2wxS3hoeUk2c3FmOWZIMHBGTlN3ZVRZVk5UbTJYS0I3MjM5CklPMTh5WGgxNXk2OS9jcEN0
    SEZrZ0JBUko5cHIzeEJTRHBGMVJRZlFTV1c5QnlmZHpPQS9rWlBKTWlFKy8raE8KNXE2L0duZTFS
    SmdFeEUyRnVBYThyamZzZnRRUEJOc1VVelByZC9tUWtKeGxYaDFVVWdoVmY5N0x1MEhhUi9ncgpl
    Yms5cWcwNzNXeXg0am93VEZoejhvQVhaWmtvZVRzcW02UHZaZENQRW1ia0Q4djVwaDdxazBLcndT
    c1BuN1ZaCmpaa0VhQnB0VlpRL2M0TmRmemdwQ2d6cDB0bDNJRWtGQ2lFREtkUlRhTzR2emhxODhU
    ZmU0TVdSaDBDY1h3TE8KK014MzZBVzBFYU55c1k1UWpPQTZqM2E4ZW42SkNhZEdQVkkzY1FJREFR
    QUJBb0lCQUN3YmlFNjU2bFJYVWJUawpDNVQ5OVRRYXVOM2xMTlAwcllGQm05MDRUSGtJZitvOW5Q
    ZFd1NDBWRWd3TmI3VmJRNnoyUk9XSU5nSG54ZzY0CndHUHEveFMzMDJtWGdXRG83NkUvdktZNE01
    V2c1MTlZVHRiMjU0dk8weEdLdkk5REJNSTBLUXRKSFQzQTZYcGkKb21hb0lyZTJmbUlwNjR5OU15
    Q1VKSFpvbFAvL1BPR2ZGS3B3amp4dlhWQ1V4VkFyRXRLN0Z5WGd1cFB6RHVZYQpXTE40V1dsSmY4
    M00rcUVmdkJuN2RmaHFKbjFVZXFnZGlpcVlCZjh3b3hMUVpKdHR3c3dKYVpCdW1wZ2hJYUtwCm1W
    Y2RQcHhvalBzLytLNGJackVWNW5IZjRZeU1wS1MvT0NtOTNTOVhaRlVKL01IbjE1UldlVThBam1V
    Y2RVL24KRlI5UFRNRUNnWUVBKzJsbHpjUFczNEtCYytXM2s2dWtnQXZLTDhCSnJDcGpKQVRReDhR
    aGh5eGJxWW5pVWhXZQowaFpISGUrZjIyZzVqWHJ0cjFZN21qUWZUYm02YmRhczJhRnJIa3NWaDdp
    N0RLdWlpVzVnSlN3aWpaelJ4R2Z2CnJ3RFFYTVZKRS93dHdMSWtaU20wcFFnV1hZZGNXS0NGY0lL
    NVBDbyt0UUliUW9MVDRhbC9DbGtDZ1lFQXlBZUMKRDFPMU9rZ1Y5RU1KTTFvVjhONXJaNHcreStE
    ZnBKTnVONGFsY25wTUw0QkNDU25zNXhlOWZ1QTJBMnJVQ2FoYQpCZFBpWTQyNDNzdmI2cUlJaHpY
    UFQ0Q2hFejYrcGZVdFJzSzYrV3BBRHNQQzNDRzFiM1dhd0U1cmJ3czhUL09TCnpuekFaMjBORTFn
    NGJBKzhvZEwzcVgwYml3UXh3WEwzK3BIRHd0a0NnWUVBN1dib1AvWUc2QVgzTWJhZ3Mrdm4KcVJY
    NDlVQlJFU2J4ZVNpbThZd3QwTk85Tm9uQ1VacWkzMlUwQUh1dTZ1TXZQWDd3QkpxY0s0KytZNG5Y
    RmpNYQpBMk9lbi90c3VEMWpPNkt6RjYxSFVyS3JhaWZFR1AvQVgvT1h6WkpwNEZwSDVlY1I0UWtS
    MEtpalhld2M4bitaCm9kVi9EdVloVXBGTHBuR2RuRUNPZXZrQ2dZQUhFL1R2TStnU3d1QTcvMjlB
    Nk93ajFNcjZKQVZJMDVFMlVwMHcKeTh2bzdCanNDVjdNMGpYMnkybENKdzdpT2hKOHNQOVdlM1Br
    VCt4OXZicnZaNEpqdm15eWhIdXVvYWEvV3BpYQppMk53VmVra1hKcjFqUi9OYk56bjl4NW9GSDZ5
    Mll5VlQrYkRBaUhYVUdUV3RndlhzZzVmYWZUaWkyaHpUdTBsCmFha0NxUUtCZ0VXcXF5M0xpSkhB
    M0lMZlB2UlQxSkdDSTlpZkpKZmM0SFl6WVdYeHJRTmJHQnVrSHVjOWQxNHcKVkVlUWxJT0d5MGs5
    UGluZi8vTEtFNDVwY1QxWC9ZdlRWaEU0TWk1MFQzYjFuQUtDZXlSNTIwYjFnV2hWdEdVQQplcjRR
    VTMzR3J1NzMxazdobHkvTzVVYTQzMWtxQnNIYU1haUtyNHhUZjAydlFqRjVXeS9rCi0tLS0tRU5E
    IFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
type: Opaque
