-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."mandataire_individuel_departement" add column "liste_blanche_id" integer
--  null;
