image:
  repository: registry.gitlab.factory.social.gouv.fr/socialgouv/emjpm/api
  tag: latest
  pullPolicy: IfNotPresent
labels: {}
deployment:
  annotations: {}
  replicaCount: 1
  imagePullSecrets: []
  port: 80
  livenessProbe:
    initialDelaySeconds: 5
    path: /
    periodSeconds: 10
    failureThreshold: 10
    timeoutSeconds: 10
  readinessProbe:
    initialDelaySeconds: 5
    path: /
    periodSeconds: 10
    failureThreshold: 10
    timeoutSeconds: 10
  resources:
    limits:
      cpu: 250m
      memory: 1024Mi
    requests:
      cpu: 10m
      memory: 384Mi
  env:
    - name: APP_URL
      value: '80'
      valueFrom:
        secretKeyRef:
          name: emjpm-secret
          key: APP_URL
    - name: HASURA_GRAPHQL_ADMIN_SECRET
      value: production
      valueFrom:
        secretKeyRef:
          name: emjpm-secret
          key: HASURA_GRAPHQL_ADMIN_SECRET
    - name: HASURA_WEB_HOOK_SECRET
      valueFrom:
        secretKeyRef:
          name: emjpm-secret
          key: HASURA_WEB_HOOK_SECRET
    - name: PGSSLMODE
      value: require
    - name: HASURA_GRAPHQL_URI
      value: 'http://${HASURA_SRV_HOST}/v1/graphql'
    - name: DATABASE_URL
      value: >-
        psql://${EMJPM_PG_USER_ENCODED}:${EMJPM_PG_PASSWORD_ENCODED}@${PG_HOST}/${POSTGRES_DATABASE_EMJPM}
    - name: PORT
      value: '80'
    - name: NODE_ENV
      value: production
    - name: SMTP_HOST
      valueFrom:
        secretKeyRef:
          name: emjpm-secret
          key: SMTP_HOST
    - name: SMTP_PORT
      valueFrom:
        secretKeyRef:
          name: emjpm-secret
          key: SMTP_PORT
    - name: SMTP_USER
      valueFrom:
        secretKeyRef:
          name: emjpm-secret
          key: SMTP_USER
    - name: SMTP_PASS
      valueFrom:
        secretKeyRef:
          name: emjpm-secret
          key: SMTP_PASS
    - name: SMTP_FROM
      valueFrom:
        secretKeyRef:
          name: emjpm-secret
          key: SMTP_FROM
    - name: SENTRY_PUBLIC_DSN
      valueFrom:
        secretKeyRef:
          name: emjpm-secret
          key: SENTRY_PUBLIC_DSN
    - name: AZURE_ACCOUNT_NAME
      valueFrom:
        secretKeyRef:
          name: emjpm-secret
          key: AZURE_ACCOUNT_NAME
    - name: AZURE_ACCOUNT_KEY
      valueFrom:
        secretKeyRef:
          name: emjpm-secret
          key: AZURE_ACCOUNT_KEY
    - name: OCMI_SYNC_FILE_ENABLED
      valueFrom:
        secretKeyRef:
          name: emjpm-secret
          key: OCMI_SYNC_FILE_ENABLED
    - name: OCMI_FILE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: emjpm-secret
          key: OCMI_FILE_PASSWORD
    - name: SENTRY_ENV
      value: '${NODE_ENV}'
    - name: AUTH_PRIVATE_KEY
      valueFrom:
        secretKeyRef:
          name: emjpm-secret
          key: AUTH_PRIVATE_KEY
    - name: AUTH_PUBLIC_KEY
      valueFrom:
        secretKeyRef:
          name: emjpm-secret
          key: AUTH_PUBLIC_KEY
  nodeSelector: {}
  tolerations: []
  affinity: {}
  initContainers: []
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/limit-connections: '2'
    nginx.ingress.kubernetes.io/limit-rpm: '60'
  hosts:
    - host: api-emjpm.dev2.fabrique.social.gouv.fr
      paths:
        - path: /
          servicePort: '${PORT}'
  tls:
    - hosts:
        - api-emjpm.dev2.fabrique.social.gouv.fr
      secretName: api-certificate
fullnameOverride: ''
nameOverride: ''
service:
  type: ClusterIP
  port: '${PORT}'
  targetPort: '${PORT}'
