-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."service_member_invitations" add column "invitation_role" text
--  null;
