version: "3"

#
# In development we can start more services
#
# Listening ports :
#
#  - 3000 : frontend
#  - 4000 : api
#  - 4001 : graphql-server
#  - 5000 : hasura
#  - 5434 : postgres
#

services:
  maildev:
    image: djfarrelly/maildev

  api:
    image: registry.gitlab.factory.social.gouv.fr/socialgouv/emjpm/api:master
    env_file: .env.build
    ports:
      - 4000:4000
    depends_on:
      - db
    links:
      - db

  graphql-server:
    image: registry.gitlab.factory.social.gouv.fr/socialgouv/emjpm/graphql-server:master
    env_file: .env.build
    ports:
      - 4001:4001

  frontend:
    image: registry.gitlab.factory.social.gouv.fr/socialgouv/emjpm/app:master
    env_file: .env.build
    ports:
      - 3000:80

  graphql-engine:
    image: registry.gitlab.factory.social.gouv.fr/socialgouv/emjpm/hasura:master
    depends_on:
      - api
      - db
      - graphql-server
    restart: unless-stopped
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:test@db:5432/emjpm
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ADMIN_SECRET: secret
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256","jwk_url": "http://api:4000/api/v2/auth/jwks"}'
      WHATEVER_URL: http://graphql-server:4001/graphql
      WEB_HOOK_URL_EMAIL_RESERVATION: http://api:4000/webhook/email-reservation
      WEB_HOOK_URL_EMAIL_CANCEL_RESERVATION: http://api:4000/webhook/email-cancel-reservation
      WEB_HOOK_URL_EMAIL_ACCOUNT_VALIDATION: http://api:4000/webhook/email-account-validation
      WEB_HOOK_URL_MESURES_IMPORT: http://api:4000/webhook/mesures-import

  db:
    image: registry.gitlab.factory.social.gouv.fr/socialgouv/emjpm/postgres:master
