.k8s-deploy-app-dev:
  extends: .base_docker_kube_image_stage
  script:
    - kubectl config view
    - envsubst < ./.k8s/app/deployment.yml > ./deployment.yml
    - envsubst < ./.k8s/app/service.yml > ./service.yml
    - envsubst < ./.k8s/app/ingress.yml > ./ingress.yml
    #
    - cat ./deployment.yml
    - kubectl apply -f ./deployment.yml
    - cat ./service.yml
    - kubectl apply -f ./service.yml
    - cat ./ingress.yml
    - kubectl apply -f ./ingress.yml


.k8s-deploy-app-prod:
  extends: .base_docker_kube_image_stage
  script:
    - envsubst < ./.k8s/certificate/certificate.yml > ./certificate.yml
    - envsubst < ./.k8s/app/deployment.yml > ./deployment.yml
    - envsubst < ./.k8s/app/service.yml > ./service.yml
    - envsubst < ./.k8s/app/ingress-prod.yml > ./ingress.yml
    #
    - kubectl apply -f ./certificate.yml
    - kubectl apply -f ./deployment.yml
    - kubectl apply -f ./service.yml
    - kubectl apply -f ./ingress.yml
