.k8s-deploy-app:
  extends: .base_docker_kube_image_stage
  script:
    - envsubst < ./.k8s/app/deployment.yml > ./deployment.yml
    - envsubst < ./.k8s/app/service.yml > ./service.yml
    - envsubst < ./.k8s/app/ingress${SUFFIX}.yml > ./ingress.yml
    #    #
    - |
      if [ -n "${COMMIT_TAG}" ]; then
        envsubst < ./.k8s/certificate/certificate.yml > ./certificate.yml;
        kubectl apply -f ./certificate.yml;
      fi
    - cat ./deployment.yml
    - cat ./service.yml
    - cat ./ingress.yml
    - kubectl apply --namespace ${K8S_NAMESPACE}-feature -f ./deployment.yml
    - kubectl apply --namespace ${K8S_NAMESPACE}-feature  -f ./service.yml
    - kubectl apply --namespace ${K8S_NAMESPACE}-feature  -f ./ingress.yml
