.k8s-deploy-app-dev:
  extends: .base_docker_kube_image_stage
  script:
    - envsubst < ./.k8s/app/deployment.yml > ./deployment.yml
    - envsubst < ./.k8s/app/service.yml > ./service.yml
    - envsubst < ./.k8s/app/ingress-dev.yml > ./ingress.yml
#    - envsubst < ./.k8s/certificate/certificate${SUFFIX}.yml > ./certificate.yml
    #    #
#    - kubectl apply -f ./certificate.yml
    - kubectl apply -f ./deployment.yml
    - kubectl apply -f ./service.yml
    - kubectl apply -f ./ingress.yml
