-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."services" add column "use_location_adresse" boolean
--  null default 'true';
