---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-db-job
  labels:
    app: init-db-job
    git/branch: ${BRANCH_NAME}
    git/commit: ${COMMIT}
    gitlab/job: "${JOB_ID}"
spec:
  template:
    metadata:
      labels:
        app: init-db-job
        git/branch: ${BRANCH_NAME}
        git/commit: ${COMMIT}
        gitlab/job: "${JOB_ID}"
    spec:
      containers:
        - name: init-db-job
          image: postgres:10-alpine
          command:
            - sh
          args:
            - -c
            - |
              sh -x /mnt/script/init-db.sh
          resources:
            requests:
              cpu: 1000m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 1Gi
          env:
            - name: BRANCH_HASH
              value: ${BRANCH_HASH}
            - name: PGUSER
              value: emjpm@emjpmdevserver
            - name: PGHOST
              value: emjpmdevserver.postgres.database.azure.com
            - name: PGPASSWORD
              value: ${MANAGED_DB_PASSWORD}
            - name: POSTGRES_EMJPM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: emjpm-secret
                  key: POSTGRES_EMJPM_PASSWORD
            - name: POSTGRES_HASURA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: emjpm-secret
                  key: POSTGRES_HASURA_PASSWORD
            - name: POSTGRES_METABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: emjpm-secret
                  key: POSTGRES_METABASE_PASSWORD
          volumeMounts:
            - mountPath: "/mnt/script"
              name: script
      restartPolicy: Never
      volumes:
        - name: script
          configMap:
            name: ${K8S_PROJECT}-init-db-${BRANCH_HASH}
