.k8s-deploy-graphql-server:
  extends: .base_docker_kube_image_stage
  script:
    # NOTE(douglasduteil): use local namespace hasura pod name
    - export HASURA_HOST=${K8S_PROJECT}-hasura-${BRANCH_HASH}
    #
    - envsubst < ./.k8s/graphql-server/deployment.yml > ./deployment.yml
    - envsubst < ./.k8s/graphql-server/service.yml > ./service.yml
    #
    - kubectl apply -f ./deployment.yml
    - kubectl apply -f ./service.yml
