.k8s-deploy-graphql-server-dev:
  extends: .base_docker_kube_image_stage
  script:
    - envsubst < ./.k8s/graphql-server/deployment.yml > ./deployment.yml
    - envsubst < ./.k8s/graphql-server/service.yml > ./service.yml
    - envsubst < ./.k8s/graphql-server/ingress.yml > ./ingress.yml
    #
    - kubectl apply -f ./deployment.yml
    - kubectl apply -f ./service.yml
    - kubectl apply -f ./ingress.yml

.k8s-deploy-graphql-server-prod:
  extends: .base_docker_kube_image_stage
  script:
    - envsubst < ./.k8s/certificate/certificate.yml > ./certificate.yml
    - envsubst < ./.k8s/graphql-server/deployment.yml > ./deployment.yml
    - envsubst < ./.k8s/graphql-server/service.yml > ./service.yml
    - envsubst < ./.k8s/graphql-server/ingress-prod.yml > ./ingress.yml
    #
    - kubectl apply -f ./certificate.yml
    - kubectl apply -f ./deployment.yml
    - kubectl apply -f ./service.yml
    - kubectl apply -f ./ingress.yml
