.k8s-deploy-graphql-server:
  extends: .base_docker_kube_image_stage
  script:
    - envsubst < ./.k8s/graphql-server/deployment.yml > ./deployment.yml
    - envsubst < ./.k8s/graphql-server/service.yml > ./service.yml
    #
    - kubectl apply -f ./deployment.yml -n ${K8S_NAMESPACE}
    - kubectl apply -f ./service.yml -n ${K8S_NAMESPACE}
