.k8s-deploy-hasura:
  extends: .base_docker_kube_image_stage
  script:
    - export POSTGRESQL_USER=$(kubectl get secret -n emjpm emjpm-secret -o jsonpath='{.data.POSTGRES_USER}' | base64 --decode)
    - export POSTGRESQL_PASSWORD=$(kubectl get secret -n emjpm emjpm-secret -o jsonpath='{.data.POSTGRES_PASSWORD}' | base64 --decode)
    #
    - envsubst < ./.k8s/hasura/deployment.yml > ./deployment.yml
    - envsubst < ./.k8s/hasura/service.yml > ./service.yml
    - envsubst < ./.k8s/hasura/ingress.yml > ./ingress.yml
    #
    - kubectl apply -f ./deployment.yml -n ${K8S_NAMESPACE}
    - kubectl apply -f ./service.yml -n ${K8S_NAMESPACE}
    - kubectl apply -f ./ingress.yml -n ${K8S_NAMESPACE}
