.k8s-deploy-hasura:
  extends: .base_docker_kube_image_stage
  script:
    #
    - envsubst < ./.k8s/hasura/deployment${SUFFIX}.yml > ./deployment.yml
    - envsubst < ./.k8s/hasura/service.yml > ./service.yml
    - envsubst < ./.k8s/hasura/ingress${SUFFIX}.yml > ./ingress.yml
    #
    - kubectl apply -f ./deployment.yml -n emjpm-feature
    - kubectl apply -f ./service.yml -n emjpm-feature
    - kubectl apply -f ./ingress.yml -n emjpm-feature
