.k8s-deploy-hasura:
  extends: .base_docker_kube_image_stage
  script:
    - export HASURA_POSTGRESQL_USER=${POSTGRESQL_USER}
    - export HASURA_POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
    #
    - envsubst < ./.k8s/hasura/deployment.yml > ./deployment.yml
    - envsubst < ./.k8s/hasura/service.yml > ./service.yml
    - envsubst < ./.k8s/hasura/ingress.yml > ./ingress.yml
    #
    - kubectl apply -f ./deployment.yml -n ${K8S_NAMESPACE}
    - kubectl apply -f ./service.yml -n ${K8S_NAMESPACE}
    - kubectl apply -f ./ingress.yml -n ${K8S_NAMESPACE}
