.k8s-deploy-hasura-dev:
  extends: .base_docker_kube_image_stage
  script:
    - envsubst < ./.k8s/hasura/deployment-dev.yml > ./deployment.yml
    - envsubst < ./.k8s/hasura/service.yml > ./service.yml
    - envsubst < ./.k8s/hasura/ingress-dev.yml > ./ingress.yml
    #
    - kubectl apply -f ./deployment.yml
    - kubectl apply -f ./service.yml
    - kubectl apply -f ./ingress.yml

.k8s-deploy-hasura-prod:
  extends: .base_docker_kube_image_stage
  script:
    - envsubst < ./.k8s/hasura/deployment-prod.yml > ./deployment.yml
    - envsubst < ./.k8s/hasura/service.yml > ./service.yml
    #
    - kubectl apply -f ./deployment.yml
    - kubectl apply -f ./service.yml
