.k8s-deploy-hasura:
  extends: .base_docker_kube_image_stage
  script:
    - export HASURA_POSTGRESQL_USER=postgres
    - export HASURA_POSTGRES_PASSWORD=$(kubectl get secret --namespace ${K8S_NAMESPACE} ${POSTGRES_HOST} -o jsonpath="{.data.postgresql-password}" | base64 --decode)
    #
    - envsubst < ./.k8s/hasura/deployment.yml > ./deployment.yml
    - envsubst < ./.k8s/hasura/service.yml > ./service.yml
    - envsubst < ./.k8s/hasura/ingress.yml > ./ingress.yml
    #
    - kubectl apply -f ./deployment.yml -n ${K8S_NAMESPACE}
    - kubectl apply -f ./service.yml -n ${K8S_NAMESPACE}
    - kubectl apply -f ./ingress.yml -n ${K8S_NAMESPACE}
