.k8s-deploy-hasura:
  extends: .base_docker_kube_image_stage
  script:
    - export POSTGRES_HASURA_USER=hasura
    - export POSTGRES_HASURA_PASSWORD=$(kubectl get secret emjpm-secret -o jsonpath='{.data.POSTGRES_HASURA_PASSWORD}' | base64 --decode)
    #
    - envsubst < ./.k8s/hasura/deployment.yml > ./deployment.yml
    - envsubst < ./.k8s/hasura/service.yml > ./service.yml
    - envsubst < ./.k8s/hasura/ingress.yml > ./ingress.yml
    #
    - kubectl apply -f ./deployment.yml
    - kubectl apply -f ./service.yml
    - kubectl apply -f ./ingress.yml
