---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ${K8S_NAMESPACE}-${CONTEXT}-${BRANCH_HASH}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ${K8S_NAMESPACE}-${CONTEXT}-${BRANCH_HASH}
        git/branch: ${BRANCH_NAME}
      annotations:
        git/commit: ${COMMIT}
        gitlab/job: "${JOB_ID}"
    spec:
      containers:
        - image: hasura/graphql-engine:v1.0.0-beta.2
          name: ${K8S_NAMESPACE}-${CONTEXT}
          imagePullPolicy: "IfNotPresent"
          ports:
          - containerPort: 8080
          env:
          - name: HASURA_GRAPHQL_DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: emjpm-secret
                key: HASURA_GRAPHQL_DATABASE_URL
          - name: HASURA_GRAPHQL_ENABLE_CONSOLE
            value: "true"
          - name: HASURA_GRAPHQL_ADMIN_SECRET
            valueFrom:
              secretKeyRef:
                name: emjpm-secret
                key: HASURA_GRAPHQL_ADMIN_SECRET
          - name: HASURA_GRAPHQL_JWT_SECRET
            value: "{\"type\": \"RS256\",\"jwk_url\": \"${API_URL}/api/auth/v2/jwks\"}"
