-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- UPDATE service_member_invitations
-- SET invitation_role = 'service'
-- WHERE invitation_role IS NULL;
