#!/bin/bash

[ -f .env ] && source .env

if [ -z "$PROJECT" ]; then
  read -p "PROJECT: " PROJECT
fi
if [ -z "$BRANCH" ] && [ -z "$PRODUCTION" ]; then
  read -p "BRANCH (v25.8.3, feature-3bbf23f) [master]: " BRANCH
fi
if [ -z "$BRANCH" ] && [ -z "$PRODUCTION" ]; then
  BRANCH="master"
fi

if [ -z "$PGDATABASE" ]; then
  if [ -z "$BRANCH" ]; then
    PGDATABASE="${PROJECT}"
  else
    PGDATABASE="${PROJECT}_`echo $BRANCH | sed 's/^feature-//g;s/\.//g'`"
  fi
fi

if [ -z "$NAMESPACE" ]; then
  if [ -z "$BRANCH" ]; then
    NAMESPACE="${PROJECT}"
  else
    NAMESPACE="${PROJECT}-`echo $BRANCH | sed 's/\./-/g'`"
  fi
fi

if [ -z "$KUBECONFIG" ] && [ -f "$PWD/config" ]; then
  export KUBECONFIG="$PWD/config"
fi

echo KUBECONFIG=$KUBECONFIG
echo BRANCH=$BRANCH
echo NAMESPACE=$NAMESPACE
echo PGDATABASE=$PGDATABASE

set +x
kubectl -n $NAMESPACE run \
  --image=registry.gitlab.factory.social.gouv.fr/devthejo/psql \
  -i \
  --tty \
  --rm \
  --restart=Never \
  psql \
  --env="PGSSLMODE=require" \
  --env="PGHOST=$PGHOST" \
  --env="PGUSER=$PGUSER" \
  --env="PGPASSWORD=$PGPASSWORD" \
  --env="PGDATABASE=$PGDATABASE"
