---
apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-job
  labels:
    app: migrate-job
    git/branch: ${BRANCH_NAME}
    git/commit: ${COMMIT}
    gitlab/job: "${JOB_ID}"
spec:
  template:
    metadata:
      labels:
        app: migrate-job
        git/branch: ${BRANCH_NAME}
        git/commit: ${COMMIT}
        gitlab/job: "${JOB_ID}"
    spec:
      containers:
        - name: migrate-job
          image: registry.gitlab.factory.social.gouv.fr/socialgouv/emjpm/knex:${IMAGE_TAG}
          command:
            - sh
          args:
            - -c
            - |
              yarn migrate
          resources:
            requests:
              cpu: 0m
              memory: 0Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: PGSSLMODE
              value: "require"
            - name: DATABASE_URL
              value: "psql://${EMJPM_PG_USER_ENCODED}:${EMJPM_PG_PASSWORD_ENCODED}@${PG_HOST}/${POSTGRES_DATABASE_EMJPM}"
            - name: NODE_ENV
              value: "${NODE_ENV}"
      restartPolicy: Never
