---
apiVersion: batch/v1
kind: Job
metadata:
  name: restore-job
  labels:
    app: restore-job
    git/branch: ${BRANCH_NAME}
    git/commit: ${COMMIT}
    gitlab/job: "${JOB_ID}"
spec:
  template:
    metadata:
      labels:
        app: restore-job
        git/branch: ${BRANCH_NAME}
        git/commit: ${COMMIT}
        gitlab/job: "${JOB_ID}"
    spec:
      containers:
        - name: restore-job
          image: postgres:10-alpine
          command:
            - sh
          args:
            - -c
            - |
              sh -x /mnt/script/reset-database.sh
              sh -x /mnt/script/restore.sh /mnt/data/$(cat /mnt/data/LATEST)
          resources:
            requests:
              cpu: 0m
              memory: 0Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: ${POSTGRES_SRV_HOST}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-postgresql
                  key: postgresql-password
            - name: POSTGRES_EMJPM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: emjpm-secret
                  key: POSTGRES_EMJPM_PASSWORD
            - name: POSTGRES_HASURA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: emjpm-secret
                  key: POSTGRES_HASURA_PASSWORD
            - name: POSTGRES_METABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: emjpm-secret
                  key: POSTGRES_METABASE_PASSWORD
          volumeMounts:
            - mountPath: "/mnt/data"
              name: volume
            - mountPath: "/mnt/script"
              name: script
      restartPolicy: Never
      volumes:
        - name: script
          configMap:
            name: ${K8S_PROJECT}-restore-configmap-${BRANCH_HASH}
        - name: volume
          azureFile:
            secretName: ${K8S_PROJECT}-azure-storage-${BRANCH_HASH}
            shareName: emjpm-backup-restore
            readOnly: false
