-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE "public"."liste_blanche" ALTER COLUMN "org_gestionnaire" TYPE BOOLEAN USING org_gestionnaire::boolean;
