apiVersion: batch/v1
kind: Job
metadata:
  generateName: build-job-
spec:
  backoffLimit: 0
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/buildkit: unconfined
        container.seccomp.security.alpha.kubernetes.io/buildkit: unconfined
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      restartPolicy: Never
      initContainers:
        - name: git-clone-repo
          image: ${GITCLONE_IMAGE}:${GITCLONE_TAG}
          command:
            - sh
            - -c
            - |
              git clone \
                --depth 1 \
                $GIT_REPOSITORY \
                --branch $GIT_BRANCH \
                --single-branch \
                /workspace
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - name: workspace
              mountPath: /workspace
        - name: docker-login
          image: ${DOCKER_IMAGE}:${DOCKER_TAG}
          env:
            - name: DOCKER_CONFIG
              value: /home/user/.docker
            - name: REGISTRY_USER
              valueFrom:
                secretKeyRef:
                  name: $REGISTRY_SECRET_NAME
                  key: $REGISTRY_USER_KEY
            - name: REGISTRY_PASS
              valueFrom:
                secretKeyRef:
                  name: $REGISTRY_SECRET_NAME
                  key: $REGISTRY_PASS_KEY
          command:
            - sh
            - -c
            - |
              echo $REGISTRY_PASS | \
                docker login --username $REGISTRY_USER --password-stdin \
                $REGISTRY_URL
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - name: home-docker
              mountPath: /home/user/.docker
      containers:
        - name: buildkit
          image: ${BUILDKITD_IMAGE}:${BUILDKIT_TAG}
          env:
            - name: BUILDKITD_FLAGS
              value: --oci-worker-no-process-sandbox
          command:
            - buildctl-daemonless.sh
          args:
            - build
            - --frontend
            - dockerfile.v0
            - --local
            - context=/workspace/$BUILD_CONTEXT
            - --local
            - dockerfile=/workspace/$BUILD_DOCKERFILE
            - --output
            - type=image,name=${REGISTRY_URL}/${REGISTRY_PUSH_PATH}:${REGISTRY_PUSH_TAG},push=true
            - --export-cache
            - mode=max,type=registry,ref=${REGISTRY_URL}/${REGISTRY_PUSH_PATH}:${REGISTRY_CACHE_TAG}
            - --import-cache
            - type=registry,ref=${REGISTRY_URL}/${REGISTRY_PUSH_PATH}:${REGISTRY_CACHE_TAG}
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - name: workspace
              readOnly: true
              mountPath: /workspace
            - name: home-docker
              mountPath: /home/user/.docker
              readOnly: false

      volumes:
        - name: workspace
          emptyDir: {}
        - name: home-docker
          emptyDir: {}