version: "3"
services:
  db:
    image: postgres:10.3
    restart: always
    container_name: emjpm-postgres
    environment:
      # master password
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      # API dedicated password
      - POSTGRES_API_USER=api
      - POSTGRES_API_USER_PASSWORD=test
      - POSTGRES_READONLY_USER_NAME=readonly
      - POSTGRES_READONLY_USER_PASSWORD=readonlyPassword
    ports:
      - "5434:5432"
    volumes:
      - emjpm-pgdata:/var/lib/postgresql/data
      - ./db/postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh
volumes:
  emjpm-pgdata:
