export const datas = [
  {
    age: 1924,
    civilite: 'madame',
    dateNomination: '2019-01-10',
    dateNominationFormated: '2019/01/10',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 1,
    latitude: 43.712,
    longitude: 7.23827,
    natureMesure: 'tutelle',
    numeroDossier: '315126646',
    numeroRg: '651654654',
    protectionChamp: 'protection_bien_personne',
    status: 'Eteindre mesure',
    ville: 'PARIS',
  },
  {
    age: 1924,
    cabinet: 'test',
    civilite: 'madame',
    dateNomination: '2007-06-05',
    dateNominationFormated: '2019/01/10',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 2,
    latitude: 43.712,
    longitude: 7.23827,
    natureMesure: 'curatelle_renforce',
    numeroDossier: '315126646',
    numeroRg: '651654654',
    protectionChamp: 'protection_bien_personne',
    status: 'Mesure en attente',
    tribunal: 'test',
    ville: 'PARIS',
  },
  {
    age: 1986,
    cabinet: 'test',
    civilite: 'madame',
    dateNomination: '2011-01-11',
    dateNominationFormated: '2019/01/10',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 3,
    latitude: 43.712,
    longitude: 7.23827,
    natureMesure: 'tutelle',
    numeroDossier: '315126646',
    numeroRg: '651654654',
    protectionChamp: 'protection_bien_personne',
    status: 'Mesure en cours',
    tribunal: 'test',
    ville: 'PARIS',
  },
  {
    age: 1927,
    cabinet: 'test',
    civilite: 'madame',
    dateNomination: '2011-01-11',
    dateNominationFormated: '2019/01/10',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 7,
    latitude: 43.712,
    longitude: 7.23827,
    natureMesure: 'tutelle',
    numeroDossier: '315126646',
    numeroRg: '651654654',
    protectionChamp: 'protection_bien',
    status: 'Mesure en cours',
    tribunal: 'test',
    ville: 'PARIS',
  },
  {
    age: 1985,
    cabinet: 'test',
    civilite: 'madame',
    dateNomination: '2011-01-11',
    dateNominationFormated: '2019/01/10',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 4,
    latitude: 43.712,
    longitude: 7.23827,
    natureMesure: 'tutelle',
    numeroDossier: '315126646',
    numeroRg: '651654654',
    protectionChamp: 'protection_bien_personne',
    status: 'Mesure en cours',
    tribunal: 'test',
    ville: 'PARIS',
  },
  {
    age: 1988,
    cabinet: 'test',
    civilite: 'madame',
    dateNomination: '2011-01-11',
    dateNominationFormated: '2019/01/10',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 5,
    latitude: 43.712,
    longitude: 7.23827,
    natureMesure: 'tutelle',
    numeroDossier: '315126646',
    numeroRg: '651654654',
    protectionChamp: 'protection_bien_personne',
    status: 'Mesure en cours',
    tribunal: 'test',
    ville: 'PARIS',
  },
  {
    age: 1985,
    cabinet: 'test',
    civilite: 'madame',
    dateNomination: '2011-01-11',
    dateNominationFormated: '2019/01/10',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 6,
    latitude: 43.712,
    longitude: 7.23827,
    natureMesure: 'tutelle',
    numeroDossier: '315126646',
    numeroRg: '651654654',
    protectionChamp: 'protection_bien_personne',
    status: 'Mesure en cours',
    tribunal: 'test',
    ville: 'PARIS',
  },
];

export const mandataireDatas = [
  {
    age: 1998,
    cabinet: 'test',
    civilite: 'madame',
    dateNomination: '2011-01-11',
    dateNominationFormated: '2019/01/10',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 3,
    latitude: 43.712,
    longitude: 7.23827,
    natureMesure: 'tutelle',
    numeroDossier: '315126646',
    numeroRg: '651654654',
    protectionChamp: 'protection_bien_personne',
    status: 'Mesure en attente',
    tribunal: 'test',
    ville: 'PARIS',
  },
  {
    age: 1998,
    cabinet: 'test',
    civilite: 'madame',
    dateNomination: '2011-01-11',
    dateNominationFormated: '2019/01/10',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 7,
    latitude: 43.712,
    longitude: 7.23827,
    natureMesure: 'tutelle',
    numeroDossier: '315126646',
    numeroRg: '651654654',
    protectionChamp: 'protection_bien_personne',
    status: 'Mesure en attente',
    tribunal: 'test',
    ville: 'PARIS',
  },
  {
    age: 1998,
    cabinet: 'test',
    civilite: 'madame',
    dateNomination: '2011-01-11',
    dateNominationFormated: '2019/01/10',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 4,
    latitude: 43.712,
    longitude: 7.23827,
    natureMesure: 'tutelle',
    numeroDossier: '315126646',
    numeroRg: '651654654',
    protectionChamp: 'protection_bien_personne',
    status: 'Mesure en attente',
    tribunal: 'test',
    ville: 'PARIS',
  },
  {
    age: 1998,
    cabinet: 'test',
    civilite: 'madame',
    dateNomination: '2011-01-11',
    dateNominationFormated: '2019/01/10',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 5,
    latitude: 43.712,
    longitude: 7.23827,
    natureMesure: 'tutelle',
    numeroDossier: '315126646',
    numeroRg: '651654654',
    protectionChamp: 'protection_bien_personne',
    status: 'Mesure en attente',
    tribunal: 'test',
    ville: 'PARIS',
  },
  {
    age: 1998,
    cabinet: 'test',
    civilite: 'madame',
    dateNomination: '2011-01-11',
    dateNominationFormated: '2019/01/10',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 6,
    latitude: 43.712,
    longitude: 7.23827,
    natureMesure: 'tutelle',
    numeroDossier: '315126646',
    numeroRg: '651654654',
    protectionChamp: 'protection_bien_personne',
    status: 'Mesure en attente',
    tribunal: 'test',
    ville: 'PARIS',
  },
];
