export const datas = [
  {
    age: 1924,
    civilite: 'F',
    dateOuverture: '2019-01-10',
    dateOuvertureFormated: '2019/01/10',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 1,
    latitude: 43.712,
    longitude: 7.23827,
    numeroDossier: '315126646',
    numeroRg: '651654654',
    status: 'Eteindre mesure',
    type: 'Tutelle aux biens et à la personne',
    ville: 'PARIS',
  },
  {
    age: 1924,
    cabinet: 'test',
    civilite: 'F',
    dateOuverture: '2007-06-05',
    dateOuvertureFormated: '2019/01/10',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 2,
    latitude: 43.712,
    longitude: 7.23827,
    numeroDossier: '315126646',
    numeroRg: '651654654',
    status: 'Mesure en attente',
    tribunal: 'test',
    type: 'curatelle renforcée aux biens et à la personne',
    ville: 'PARIS',
  },
  {
    age: 1986,
    cabinet: 'test',
    civilite: 'F',
    dateOuverture: '2011-01-11',
    dateOuvertureFormated: '2019/01/10',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 3,
    latitude: 43.712,
    longitude: 7.23827,
    numeroDossier: '315126646',
    numeroRg: '651654654',
    status: 'Mesure en cours',
    tribunal: 'test',
    type: 'Tutelle',
    ville: 'PARIS',
  },
  {
    age: 1927,
    cabinet: 'test',
    civilite: 'F',
    dateOuverture: '2011-01-11',
    dateOuvertureFormated: '2019/01/10',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 7,
    latitude: 43.712,
    longitude: 7.23827,
    numeroDossier: '315126646',
    numeroRg: '651654654',
    status: 'Mesure en cours',

    tribunal: 'test',
    type: 'Tutelle',
    ville: 'PARIS',
  },
  {
    age: 1985,
    cabinet: 'test',
    civilite: 'F',
    dateOuverture: '2011-01-11',
    dateOuvertureFormated: '2019/01/10',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 4,
    latitude: 43.712,
    longitude: 7.23827,
    numeroDossier: '315126646',
    numeroRg: '651654654',
    status: 'Mesure en cours',
    tribunal: 'test',
    type: 'Tutelle',
    ville: 'PARIS',
  },
  {
    age: 1988,
    cabinet: 'test',
    civilite: 'F',
    dateOuverture: '2011-01-11',
    dateOuvertureFormated: '2019/01/10',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 5,
    latitude: 43.712,
    longitude: 7.23827,
    numeroDossier: '315126646',
    numeroRg: '651654654',
    status: 'Mesure en cours',
    tribunal: 'test',
    type: 'Tutelle',
    ville: 'PARIS',
  },
  {
    age: 1985,
    cabinet: 'test',
    civilite: 'F',
    dateOuverture: '2011-01-11',
    dateOuvertureFormated: '2019/01/10',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 6,
    latitude: 43.712,
    longitude: 7.23827,
    numeroDossier: '315126646',
    numeroRg: '651654654',
    status: 'Mesure en cours',
    tribunal: 'test',
    type: 'Tutelle',
    ville: 'PARIS',
  },
];

export const mandataireDatas = [
  {
    age: 1998,
    cabinet: 'test',
    civilite: 'F',
    dateOuverture: '2011-01-11',
    dateOuvertureFormated: '2019/01/10',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 3,
    latitude: 43.712,
    longitude: 7.23827,
    numeroDossier: '315126646',
    numeroRg: '651654654',
    status: 'Mesure en attente',
    tribunal: 'test',
    type: 'Tutelle',
    ville: 'PARIS',
  },
  {
    age: 1998,
    cabinet: 'test',
    civilite: 'F',
    dateOuverture: '2011-01-11',
    dateOuvertureFormated: '2019/01/10',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 7,
    latitude: 43.712,
    longitude: 7.23827,
    numeroDossier: '315126646',
    numeroRg: '651654654',
    status: 'Mesure en attente',
    tribunal: 'test',
    type: 'Tutelle',
    ville: 'PARIS',
  },
  {
    age: 1998,
    cabinet: 'test',
    civilite: 'F',
    dateOuverture: '2011-01-11',
    dateOuvertureFormated: '2019/01/10',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 4,
    latitude: 43.712,
    longitude: 7.23827,
    numeroDossier: '315126646',
    numeroRg: '651654654',
    status: 'Mesure en attente',
    tribunal: 'test',
    type: 'Tutelle',
    ville: 'PARIS',
  },
  {
    age: 1998,
    cabinet: 'test',
    civilite: 'F',
    dateOuverture: '2011-01-11',
    dateOuvertureFormated: '2019/01/10',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 5,
    latitude: 43.712,
    longitude: 7.23827,
    numeroDossier: '315126646',
    numeroRg: '651654654',
    status: 'Mesure en attente',
    tribunal: 'test',
    type: 'Tutelle',
    ville: 'PARIS',
  },
  {
    age: 1998,
    cabinet: 'test',
    civilite: 'F',
    dateOuverture: '2011-01-11',
    dateOuvertureFormated: '2019/01/10',
    hasAccepting: false,
    hasAddingNotes: false,
    hasClosing: false,
    hasEditing: false,
    hasReactivating: false,
    hasRemoving: false,
    href: '/mesure',
    id: 6,
    latitude: 43.712,
    longitude: 7.23827,
    numeroDossier: '315126646',
    numeroRg: '651654654',
    status: 'Mesure en attente',
    tribunal: 'test',
    type: 'Tutelle',
    ville: 'PARIS',
  },
];
