#

.quality_stage: &quality_stage
  stage: "Code Quality"
  dependencies: []

.node_stage: &node_stage
  image: "node:10"
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  before_script:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$PATH"
    #
    - yarn --frozen-lockfile

Quality tests:
  <<: *quality_stage
  <<: *node_stage
  script:
    - yarn build
    - yarn lint
    - yarn export
