apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodejs.fullname" . }}
  labels:
{{ include "nodejs.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "nodejs.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
