#!/usr/bin/env bash

function getRandomEmoji {
  emojis=("🐵" "🐒" "🦍" "🐶" "🐕" "🐩" "🐺" "🦊" "🐱" "🐈" "🦁" "🐯" "🐅" "🐆" "🐴" "🐎" "🦄" "🦓" "🦌" "🐮" "🐂" "🐃" "🐄" "🐷" "🐖" "🐗" "🐽" "🐏" "🐑" "🐐" "🐪" "🐫" "🦒" "🐘" "🦏" "🐭" "🐁" "🐀" "🐹" "🐰" "🐇" "🐿" "🦔" "🦇" "🐻" "🐨" "🐼" "🐾" "🦃" "🐔" "🐓" "🐣" "🐤" "🐥" "🐦" "🐧" "🕊" "🦅" "🦆" "🦉" "🐸" "🐊" "🐢" "🦎" "🐍" "🐲" "🐉" "🦕" "🦖" "🐳" "🐋" "🐬" "🐟" "🐠" "🐡" "🦈" "🐙" "🐚" "🦀" "🦐" "🦑" "🐌" "🦋" "🐛" "🐜" "🐝" "🐞" "🦗" "🕷" "🕸" "🦂" "💐" "🌸" "💮" "🏵" "🌹" "🥀" "🌺" "🌻" "🌼" "🌷" "🌱" "🌲" "🌳" "🌴" "🌵" "🌾" "🌿" "☘" "🍀" "🍁" "🍂" "🍃" "🍇" "🍈" "🍉" "🍊" "🍋" "🍌" "🍍" "🍎" "🍏" "🍐" "🍑" "🍒" "🍓" "🥝" "🍅" "🥥" "" "🥑" "🍆" "🥔" "🥕" "🌽" "🌶" "🥒" "🥦" "🍄" "🥜" 🌰)
  echo ${emojis[$RANDOM % ${#emojis[@]} ]}
}

function getLastVersionChanges {
  STARTFLAG="false"
  random_emoji=`getRandomEmoji`
  while read LINE; do
    if [ "$STARTFLAG" == "true" ]; then
      if echo "$LINE" | grep -q -P '^## \[((\d+))\.(\d+)\.(\d+)\]'; then
        exit
      else
        echo "$LINE"
      fi
    elif echo "$LINE" | grep -q -P '^## \[(\d+)\.(\d+)\.(\d+)\]'; then
      echo -n "$LINE" | sed -r 's/^## \[(.*)\](.*)\((.*)\)/## '$random_emoji' [\1]\2 (\3)/'
      echo " deploying on production 🚀"
      STARTFLAG="true"
      continue
    fi
  done < $1
}

function getDevLink {
  VERSION=`jq -r .version lerna.json`
  VERSION_SLUG=`echo $VERSION | sed 's/\./-/g'`
  echo "-----"
  echo "https://v$VERSION_SLUG-emjpm.dev2.fabrique.social.gouv.fr/"
}

function getReleaseNote {
  getLastVersionChanges CHANGELOG.md | sed '/^$/d'
  getDevLink
}

getReleaseNote