#!/bin/sh
set -e

if [ -z "$1" ]; then
  echo "missing branch argument" >> /dev/stderr
  exit 1
fi

for BRANCH in "$@"; do
  echo "syncing branch $BRANCH"

  if [ -n "$(git diff)" ]; then
    STASHING=1
    git stash
  fi

  git checkout $BRANCH
  git reset --hard master
  git push --follow-tags --force
  git checkout master

  if [ -n "$STASHING" ]; then
    git stash apply
  fi


done

