#!/bin/sh
set -e

if [ -z "$1" ]; then
  echo "missing branch argument" >> /dev/stderr
  exit 1
fi

FROM_BRANCH=$(git branch --show-current)

for BRANCH in "$@"; do
  echo "syncing branch $BRANCH with $FROM_BRANCH"

  if [ -n "$(git diff)" ]; then
    STASHING=1
    git stash
  fi

  git checkout $BRANCH
  git reset --hard $FROM_BRANCH
  git push --follow-tags --force
  git checkout $FROM_BRANCH

  if [ -n "$STASHING" ]; then
    git stash apply
  fi


done

