-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."mesure_en_attente_reouverture" add column "greffier_id" integer
--  null;
