-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- DROP FUNCTION IF EXISTS hdb_catalog."notify_hasura_lb_update_lb_user_departement_DELETE"() CASCADE;
--
-- DROP FUNCTION IF EXISTS hdb_catalog."notify_hasura_lb_update_lb_user_departement_INSERT"() CASCADE;
--
-- DROP FUNCTION IF EXISTS hdb_catalog."notify_hasura_lb_update_lb_user_departement_UPDATE"() CASCADE;
--
-- DROP FUNCTION IF EXISTS hdb_catalog."notify_hasura_lb_update_lb_user_etablissement_DELETE"() CASCADE;
--
-- DROP FUNCTION IF EXISTS hdb_catalog."notify_hasura_lb_update_lb_user_etablissement_INSERT"() CASCADE;
--
-- DROP FUNCTION IF EXISTS hdb_catalog."notify_hasura_lb_update_lb_user_etablissement_UPDATE"() CASCADE;
--
-- DROP FUNCTION IF EXISTS hdb_catalog."notify_hasura_lb_update_service_departements_DELETE"() CASCADE;
--
-- DROP FUNCTION IF EXISTS hdb_catalog."notify_hasura_lb_update_service_departements_INSERT"() CASCADE;
--
-- DROP FUNCTION IF EXISTS hdb_catalog."notify_hasura_lb_update_service_departements_UPDATE"() CASCADE;
