#

Install knex:
  extends: .base_yarn_workspace_install
  variables:
    CONTEXT: knex
  before_script:
    - find packages -maxdepth 1 -type d -not -name knex | tail -n +2 | xargs rm -rf
  artifacts:
    expire_in: 30 mins
    paths:
      - node_modules
      - packages/knex/node_modules

#

Lint @emjpm/knex:
  extends: .quality_stage
  image: node:12-alpine
  needs:
    - Install knex
  dependencies:
    - Install knex
  script:
    - yarn workspace @emjpm/knex lint

Test @emjpm/knex:
  extends: .quality_stage
  image: node:12-alpine
  needs:
    - Install knex
  dependencies:
    - Install knex
  services:
    - name: postgres:10-alpine
  allow_failure: true
  retry: 1
  timeout: 2 minutes
  variables:
    DATABASE_URL: psql://postgres:@localhost/emjpm
    PGHOST: localhost
    PGUSER: postgres
  before_script:
    - apk add --update --no-cache postgresql=~11
    - psql --version
    #
    - pg_isready -h localhost
  script:
    - sh -x docker/postgres/postgres-init.sh
    - yarn workspace @emjpm/knex test
