#!/usr/bin/env bash

function getLastVersionChanges {
  STARTFLAG="false"
  while read LINE; do
    if [ "$STARTFLAG" == "true" ]; then
      if echo "$LINE" | grep -q -e '^## \['; then
        exit
      else
        echo "$LINE"
      fi
    elif echo "$LINE" | grep -q -e '^# \['; then
      echo -n "$LINE" | sed -r 's/^# \[(.*)\].*\((.*)\)/# 🚀 [\1] (\2)/'
      echo " deploying on production"
      STARTFLAG="true"
      continue
    fi
  done < $1
}

getLastVersionChanges CHANGELOG.md | sed '/^$/d'