#!/usr/bin/env bash

set -e

if [ -z "$GH_TOKEN" ] && [ -f .gh-token ]; then
  export GH_TOKEN=`cat .gh-token`
fi
if [ -z "$GH_TOKEN" ]; then
  echo "missing \$GH_TOKEN env variable"
  echo "go to https://github.com/settings/tokens to generate one with 'repo' scope"
  echo "then store it in .gh-token"
  exit 1;
fi

export CI=true

if [ -z "$YARN_RELEASE_ENABLE_TEST" ]; then
  yarn test
fi

lerna version --force-publish --yes

if [ -z "$YARN_RELEASE_ENABLE_WAIT" ]; then
  url="https://api-emjpm.fabrique.social.gouv.fr"
  interval_in_seconds=2
  result=$(cat lerna.json | jq -r ".version");
  path=".version"
  printf "waiting '$url' for '$result'\n"
  while true; do
  	x=$(curl $url -s | jq -r $path);
  	printf "\r$(date +%H:%M:%S): $x";
  	if [[ "$x" == "$result" ]]; then
  		break;
  	fi;
  	sleep $interval_in_seconds;
  done
fi