#!/usr/bin/env bash

set -e

if [ -z "$GH_TOKEN" ] && [ -f .gh-token ]; then
  export GH_TOKEN=`cat .gh-token`
fi
if [ -z "$GH_TOKEN" ]; then
  echo "missing \$GH_TOKEN env variable"
  echo "go to https://github.com/settings/tokens to generate one with 'repo' scope"
  echo "then store it in .gh-token"
  exit 1;
fi

export CI=true

if [ -n "$YARN_RELEASE_ENABLE_TEST" ]; then
  yarn test
fi

lerna version --force-publish --yes