extends:
  - "@socialgouv/eslint-config-react"

rules:
  import/no-named-as-default: off
  jsx-a11y/anchor-is-valid: off
  jsx-a11y/click-events-have-key-events: off
  jsx-a11y/label-has-for: off
  jsx-a11y/no-static-element-interactions: off
  prefer-const: 2
  react/prop-types: off
