env:
  browser: true
  es2021: true
extends:
  - plugin:prettier/recommended
  - plugin:import/recommended
  - plugin:jsx-a11y/recommended
  - plugin:react-hooks/recommended
  - prettier/react
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2021
  sourceType: module
plugins:
  - sort-keys-fix
  - react
settings:
  react:
    version: detect
ignorePatterns:
  - build
  - node_modules
