#!/bin/sh

set -e

set -a
source $(dirname $0)/.env-k8s
set +a

if [ -n "$(kubectl get namespace $K8SCI_K8S_DEPLOY_NS 2>/dev/null)" ]; then
  exit 0
fi

$(dirname $0)/k8s-ns-create
$(dirname $0)/k8s-ns-copy-secrets

# $(dirname $0)/db-create
$(dirname $0)/db-restore-anonymized
