#!/bin/bash

set -e

if [ -z "$(kubectl get namespace $K8SCI_K8S_DEPLOY_NS 2>/dev/null)" ]; then
  $(dirname $0)/k8s-ns-create
  $(dirname $0)/k8s-ns-copy-secrets

  # $(dirname $0)/db-create
  $(dirname $0)/db-restore-anonymized
fi
