#!/bin/bash

set -e

set -a
source $(dirname $0)/.env-db
set +a

cat ./.k8sci/scripts/jobs/db-create-job.yml | gomplate | kubectl apply -f -
kubectl wait --for=condition=complete "job/db-create-${K8SCI_GID}" --timeout=600s