#!/bin/bash

set -a
source $(dirname $0)/.env-db
set +a

if psql -lqt | cut -d \| -f 1 | grep -qw "$DB_NAME"; then
  exit 0
fi

$(dirname $0)/scripts/db-create
$(dirname $0)/scripts/db-restore-anonymized