#!/bin/sh

set -e

set -a
source $(dirname $0)/.env-k8s
set +a

kubectl create -f - <<EOF
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    field.cattle.io/projectId: $RANCHER_CLUSTER_ID:$RANCHER_PROJECT_ID
  labels:
    cert: wildcard
    field.cattle.io/projectId: $RANCHER_PROJECT_ID
  name: $K8SCI_K8S_DEPLOY_NS
EOF
