#!/bin/bash

set -e

set -a
source $(dirname $0)/.env-k8s
set +a

# copy secrets to new namespace
SECRET_NS="${K8SCI_PROJECT}-secret"
SECRET_NAME="${K8SCI_PROJECT}-secret"
kubectl -n $SECRET_NS get secret $SECRET_NAME -o json \
  | jq 'del(.metadata["namespace","creationTimestamp","resourceVersion","selfLink","uid"])' \
  | kubectl -n $K8SCI_K8S_DEPLOY_NS apply -f -
