#!/bin/bash

retval_complete=1
retval_failed=1
while [[ $retval_complete -ne 0 ]] && [[ $retval_failed -ne 0 ]]; do
  sleep 2
  output=$(kubectl --namespace=$K8SCI_NS \
    wait --for=condition=complete $JOB --timeout=0 2>&1)
  retval_complete=$?
  output=$(kubectl --namespace=$K8SCI_NS \
    wait --for=condition=failed $JOB --timeout=0 2>&1)
  retval_failed=$?
done
if [ $retval_failed -eq 0 ]; then
  echo "$JOB failed"
  exit 1
else
  echo "$JOB complete"
fi