-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- DROP FUNCTION public.search_ti_view_lb_tis(search text, departementcode text, tiid integer);
-- DROP FUNCTION public.locate_ti_view_lb_tis(lat double precision, lon double precision);
-- DROP VIEW view_lb_tis;
