apiVersion: batch/v1
kind: Job
metadata:
  name: db-anonymize-{{.Env.K8SCI_GID}}
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: anonymise-job
          image: postgres:10-alpine
          command:
            - psql {{.DB_NAME}} <<EOF
{{file.Read ".k8sci/scripts/jobs/db-anonymize.sql" | strings.Indent 14 }}
              EOF
          env:
            - name: PGSSLMODE
              value: "require"
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: psql-creds
                  key: PGHOST
            - name: DB_NAME
              value: {{.Env.DB_NAME}}
            - name: psql-creds
              secret:
                secretName: {{.Env.PSQL_CREDS_SECRET_NAME}}
      restartPolicy: Never