apiVersion: batch/v1
kind: Job
metadata:
  name: pipeline-{{.Env.K8SCI_GID}}-job-db-anonymize
  labels:
    app.kubernetes.io/managed-by: k8sci
    k8sci/gid: "{{.Env.K8SCI_GID}}"
    k8sci/type: job
    k8sci/job: db-anonymize
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: k8sci
        k8sci/gid: "{{.Env.K8SCI_GID}}"
        k8sci/type: job
        k8sci/job: db-anonymize
    spec:
      restartPolicy: Never
      containers:
        - name: anonymise-job
          image: postgres:10-alpine
          command:
            - /bin/sh
            - -c
            - |
              psql $DB_NAME <<'EOF'
{{file.Read ".k8sci/scripts/jobs/db-anonymize.sql" | strings.Indent 14 }}
              EOF
          env:
            - name: PGSSLMODE
              value: "require"
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: psql-creds
                  key: PGHOST
            - name: DB_NAME
              value: {{.Env.DB_NAME}}
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: psql-creds
                  key: ADMIN_PGUSER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: psql-creds
                  key: ADMIN_PGPASSWORD