apiVersion: batch/v1
kind: Job
metadata:
  name: db-restore-{{.Env.K8SCI_GID}}
spec:
  template:
    spec:
      containers:
        - name: restore-job
          image: postgres:10-alpine
          command:
            - sh
            - -c
            - |
              psql postgres <<EOF
                SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE pid <> pg_backend_pid() AND datname = '${DB_NAME}';
                DROP DATABASE IF EXISTS ${DB_NAME};
                CREATE DATABASE ${DB_NAME} WITH OWNER = emjpm;
              EOF
              pg_isready
              pg_restore \
                --no-owner \
                --no-acl \
                --exit-on-error \
                --format=c \
                --verbose \
                --dbname ${DB_NAME} \
                /data/$(cat /data/LATEST)

              psql -v ON_ERROR_STOP=1 ${DB_NAME}  <<-EOSQL
                GRANT CONNECT ON DATABASE ${DB_NAME} TO ${DEPLOYMENT_PGUSER};
                GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DEPLOYMENT_PGUSER};

                DELETE FROM hdb_catalog.event_invocation_logs;
                DELETE FROM hdb_catalog.event_log;
                DELETE FROM hdb_catalog.event_triggers ;
              EOSQL
          resources:
            requests:
              cpu: 0m
              memory: 0Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: PGSSLMODE
              value: "require"
            - name: PGUSER
              value: {{.Env.PGUSER}}
            - name: PGPASSWORD
              value: {{.Env.PGPASSWORD}}
            - name: PGHOST
              value: {{.Env.PGHOST}}
            - name: DB_NAME
              value: {{.Env.DB_NAME}}
          volumeMounts:
            - mountPath: "/data"
              name: data
      restartPolicy: Never
      volumes:
        - name: data
          azureFile:
            secretName: {{.Env.K8SCI_PROJECT}}-azure-storage
            shareName: emjpm-backup-restore
            readOnly: false
