apiVersion: batch/v1
kind: Job
metadata:
  name: db-reset-{{.Env.K8SCI_GID}}
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: reset-job
          image: postgres:10-alpine
          command:
            - sh
            - -c
            - |
              psql postgres <<EOF
                SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE pid <> pg_backend_pid() AND datname = '{{.Env.DB_NAME}}';
                DROP DATABASE IF EXISTS {{.Env.DB_NAME}};
                CREATE DATABASE {{.Env.DB_NAME}} WITH OWNER = {{.Env.DEPLOYMENT_PGUSER}};
              EOF
          resources:
            requests:
              cpu: 0m
              memory: 0Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: PGSSLMODE
              value: "require"
            - name: PGUSER
              value: >
                {{.Env.PGUSER}}
            - name: PGPASSWORD
              value: >
                {{.Env.PGPASSWORD}}
            - name: PGHOST
              value: {{.Env.PGHOST}}
            - name: DB_NAME
              value: {{.Env.DB_NAME}}
          volumeMounts:
            - mountPath: "/data"
              name: data
      restartPolicy: Never