---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Env.K8SCI_PROJECT}}-azure-storage-{{.Env.AZURE_STORAGE_SECRET_SUFFIX}}
type: Opaque
data:
  azurestorageaccountname: {{.Env.AZURE_STORAGE_ACCOUNT_NAME}}
  azurestorageaccountkey: {{.Env.AZURE_STORAGE_ACCOUNT_KEY}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-restore-{{.Env.K8SCI_GID}}
spec:
  template:
    spec:
      containers:
        - name: restore-job
          image: postgres:10-alpine
          command:
            - sh
            - -c
            - |
              pg_restore \
                --no-owner \
                --no-acl \
                --exit-on-error \
                --format=c \
                --verbose \
                --dbname ${DB_NAME} \
                /data/$(cat /data/LATEST)

              psql -v ON_ERROR_STOP=1 ${DB_NAME}  <<-EOSQL
                GRANT CONNECT ON DATABASE ${DB_NAME} TO ${DEPLOYMENT_PGUSER};
                GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DEPLOYMENT_PGUSER};

                DELETE FROM hdb_catalog.event_invocation_logs;
                DELETE FROM hdb_catalog.event_log;
                DELETE FROM hdb_catalog.event_triggers ;
              EOSQL
          resources:
            requests:
              cpu: 0m
              memory: 0Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: PGSSLMODE
              value: "require"
            - name: PGUSER
              value: "{{.Env.PGUSER}}"
            - name: PGPASSWORD
              value: |
                {{.Env.PGPASSWORD}}
            - name: PGHOST
              value: "{{.Env.PGHOST}}"
            - name: DB_NAME
              value: "{{.Env.DB_NAME}}"
          volumeMounts:
            - mountPath: "/data"
              name: data
      restartPolicy: Never
      volumes:
        - name: data
          azureFile:
            secretName: {{.Env.K8SCI_PROJECT}}-azure-storage-{{.Env.DB_NAME}}
            shareName: {{.Env.K8SCI_PROJECT}}-backup-restore
            readOnly: false
