INSERT INTO public.regions (id, nom) VALUES (1, 'Guadeloupe');
INSERT INTO public.regions (id, nom) VALUES (2, 'Martinique');
INSERT INTO public.regions (id, nom) VALUES (3, 'Guyane');
INSERT INTO public.regions (id, nom) VALUES (4, 'La Réunion');
INSERT INTO public.regions (id, nom) VALUES (6, 'Mayotte');
INSERT INTO public.regions (id, nom) VALUES (11, 'Île-de-France');
INSERT INTO public.regions (id, nom) VALUES (24, 'Centre-Val de Loire');
INSERT INTO public.regions (id, nom) VALUES (27, 'Bourgogne-Franche-Comté');
INSERT INTO public.regions (id, nom) VALUES (28, 'Normandie');
INSERT INTO public.regions (id, nom) VALUES (32, 'Hauts-de-France');
INSERT INTO public.regions (id, nom) VALUES (44, 'Grand Est');
INSERT INTO public.regions (id, nom) VALUES (52, 'Pays de la Loire');
INSERT INTO public.regions (id, nom) VALUES (53, 'Bretagne');
INSERT INTO public.regions (id, nom) VALUES (75, 'Nouvelle-Aquitaine');
INSERT INTO public.regions (id, nom) VALUES (76, 'Occitanie');
INSERT INTO public.regions (id, nom) VALUES (84, 'Auvergne-Rhône-Alpes');
INSERT INTO public.regions (id, nom) VALUES (93, 'Provence-Alpes-Côte d''Azur');
INSERT INTO public.regions (id, nom) VALUES (94, 'Corse');
SELECT pg_catalog.setval('public.regions_id_seq', 1, false);
