.k8s-deploy-api-dev:
  image:
    name: $CI_REGISTRY/$IMAGE_INFRA_BASE_NAME/docker-kube:latest
    entrypoint: [""]
  before_script:
  - /apps/create-kubeconfig.sh
  - envsubst < ./.k8s/api/deployment.yml > ./deployment.yml
  - envsubst < ./.k8s/api/service.yml > ./service.yml
  - envsubst < ./.k8s/api/ingress.yml > ./ingress.yml
  script:
  - kubectl apply -f ./deployment.yml
  - kubectl apply -f ./service.yml
  - kubectl apply -f ./ingress.yml


.k8s-deploy-api-prod:
  image:
    name: $CI_REGISTRY/$IMAGE_INFRA_BASE_NAME/docker-kube:latest
    entrypoint: [""]
  before_script:
  - /apps/create-kubeconfig.sh
  - envsubst < ./.k8s/api/deployment-prod.yml > ./deployment.yml
  - envsubst < ./.k8s/api/service.yml > ./service.yml
  - envsubst < ./.k8s/api/ingress-prod.yml > ./ingress.yml
  script:
  - kubectl apply -f ./deployment.yml
  - kubectl apply -f ./service.yml
  - kubectl apply -f ./ingress.yml
