.k8s-deploy-api-dev:
  image:
    name: $CI_REGISTRY/$IMAGE_INFRA_BASE_NAME/docker-kube:latest
    entrypoint: [""]
  before_script:
  - /apps/create-kubeconfig.sh
  - envsubst < k8s/api/deployment.yml > k8s/api/deployment-emjpm.yml
  - envsubst < k8s/api/service.yml > k8s/api/service-emjpm.yml
  - envsubst < k8s/api/ingress.yml > k8s/api/ingress-emjpm.yml
  script:
  - kubectl apply -f k8s/api/deployment-emjpm.yml
  - kubectl apply -f k8s/api/service-emjpm.yml
  - kubectl apply -f k8s/api/ingress-emjpm.yml
  allow_failure: false


.k8s-deploy-api-prod:
  image:
    name: $CI_REGISTRY/$IMAGE_INFRA_BASE_NAME/docker-kube:latest
    entrypoint: [""]
  before_script:
  - /apps/create-kubeconfig.sh
  - envsubst < k8s/api/deployment-prod.yml > k8s/api/deployment-emjpm.yml
  - envsubst < k8s/api/service.yml > k8s/api/service-emjpm.yml
  - envsubst < k8s/api/ingress-prod.yml > k8s/api/ingress-emjpm-prod.yml
  script:
  - kubectl apply -f k8s/api/deployment-emjpm.yml
  - kubectl apply -f k8s/api/service-emjpm.yml
  - kubectl apply -f k8s/api/ingress-emjpm-prod.yml
  allow_failure: false
