---
apiVersion: batch/v1
kind: Job
metadata:
  name: dataset
  labels:
    app: dataset
spec:
  template:
    metadata:
      labels:
        app: dataset
        git/branch: ${BRANCH_NAME}
        git/commit: ${COMMIT}
        gitlab/job: "${JOB_ID}"
    spec:
      containers:
        - name: dataset
          image: registry.gitlab.factory.social.gouv.fr/socialgouv/emjpm/knex:${IMAGE_TAG}
          command: ["sh"]
          args: ["-x", "/dataset/inject-dataset.sh"]
          env:
            - name: PGSSLMODE
              value: "require"
            - name: DATABASE_URL
              value: "psql://${EMJPM_PG_USER_ENCODED}:${EMJPM_PG_PASSWORD_ENCODED}@${PG_HOST}/${POSTGRES_DATABASE_EMJPM}"
            - name: NODE_ENV
              value: "${NODE_ENV}"
          volumeMounts:
            - name: dataset
              mountPath: /dataset
          resources:
            requests:
              cpu: 0m
              memory: 0Mi
            limits:
              cpu: 500m
              memory: 256Mi
      volumes:
        - name: dataset
          configMap:
            name: dataset-configmap
      restartPolicy: Never
