---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ${K8S_PROJECT}-backup-${BRANCH_HASH}
  labels:
    app: ${K8S_PROJECT}-backup-${BRANCH_HASH}
    git/branch: ${BRANCH_NAME}
    git/commit: ${COMMIT}
    gitlab/job: "${JOB_ID}"
spec:
  schedule: "0 7 * * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 1800
      template:
        spec:
          containers:
            #
            #
            #

            - name: backup
              image: postgres:10
              command: ["sh", "-x"]
              args: ["/mnt/script/backup.sh"]
              resources:
                requests:
                  cpu: 75m
                  memory: 32Mi
                limits:
                  cpu: 100m
                  memory: 64Mi
              env:
                - name: PGHOST
                  value: ${K8S_PROJECT}-postgres-${BRANCH_HASH}
                - name: PGUSER
                  value: emjpm
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: emjpm-secret
                      key: POSTGRES_EMJPM_PASSWORD
              volumeMounts:
                - mountPath: "/mnt/data"
                  name: data
                - mountPath: "/mnt/script"
                  name: script

            #
            #
            #

            - name: postgres
              image: postgres:10
              resources:
                requests:
                  cpu: 75m
                  memory: 32Mi
                limits:
                  cpu: 100m
                  memory: 64Mi
              ports:
                - containerPort: 5432
              env:
                - name: PGUSER
                  value: postgres

            #
            #
            #

            - name: anonymize
              image: postgres:10
              command: ["sh", "-x"]
              args:
                - /mnt/script/anonymous.sh
              resources:
                requests:
                  cpu: 75m
                  memory: 32Mi
                limits:
                  cpu: 100m
                  memory: 64Mi
              env:
                - name: PGHOST
                  value: localhost
                - name: PGUSER
                  value: postgres
              volumeMounts:
                - mountPath: "/mnt/data"
                  name: data
                - mountPath: "/mnt/anonymous"
                  name: anonymous
                - mountPath: "/mnt/script"
                  name: script

            #
            #
            #
          restartPolicy: OnFailure
          volumes:
            - name: script
              configMap:
                name: ${K8S_PROJECT}-backup-configmap-${BRANCH_HASH}
            - name: data
              azureFile:
                secretName: azure-backup-volume-secret
                shareName: emjpm
                readOnly: false
            - name: anonymous
              azureFile:
                secretName: azure-anonymous-volume-secret
                shareName: emjpm
                readOnly: false
