---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ${K8S_PROJECT}-backup-${BRANCH_HASH}
  labels:
    app: ${K8S_PROJECT}-backup-${BRANCH_HASH}
    git/branch: ${BRANCH_NAME}
    git/commit: ${COMMIT}
    gitlab/job: "${JOB_ID}"
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: postgres:10
              command: ["sh"]
              args: ["/script/backup.sh"]
              resources:
                requests:
                  cpu: 300m
                  memory: 512Mi
                limits:
                  cpu: 300m
                  memory: 512Mi
              env:
                - name: PGHOST
                  value: ${POSTGRES_HOST}
                - name: PGUSER
                  value: hasura
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: emjpm-secret
                      key: POSTGRES_HASURA_PASSWORD
              volumeMounts:
                - mountPath: "/unsafe_data"
                  name: unsafe_data
                - mountPath: "/script"
                  name: script
          restartPolicy: OnFailure
          volumes:
            - name: script
              configMap:
                name: ${K8S_PROJECT}-backup-configmap-${BRANCH_HASH}
            - name: unsafe_data
              azureFile:
                secretName: azure-backup-volume-secret
                shareName: emjpm
                readOnly: false
            - name: anonymous
              azureFile:
                secretName: azure-backup-volume-secret
                shareName: emjpm
                readOnly: false
