apiVersion: batch/v1
kind: Job
metadata:
  generateName: build-job-
spec:
  backoffLimit: 0
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/buildkit: unconfined
        container.seccomp.security.alpha.kubernetes.io/buildkit: unconfined
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      restartPolicy: Never
      initContainers:
        - name: git-clone-repo
          image: alpine/git:v2.30.0
          command:
            - sh
            - -c
            - |
              git clone \
                --depth 1 \
                https://github.com/SocialGouv/emjpm \
                --branch master --single-branch \
                /workspace
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - name: workspace
              mountPath: /workspace
        - name: docker-login
          image: docker:stable
          env:
            - name: DOCKER_CONFIG
              value: /home/user/.docker
            - name: REGISTRY_USER
              valueFrom:
                secretKeyRef:
                  name: docker-creds
                  key: user
            - name: REGISTRY_PASS
              valueFrom:
                secretKeyRef:
                  name: docker-creds
                  key: pass
          command:
            - sh
            - -c
            - |
              echo $REGISTRY_PASS | \
                docker login --username $REGISTRY_USER --password-stdin \
                registry.dev2.fabrique.social.gouv.fr
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - name: home-docker
              mountPath: /home/user/.docker
      containers:
        - name: buildkit
          # image: moby/buildkit:master-rootless
          image: moby/buildkit:v0.8.1-rootless
          env:
            - name: BUILDKITD_FLAGS
              value: --oci-worker-no-process-sandbox
          command:
            - buildctl-daemonless.sh
          args:
            - build
            - --frontend
            - dockerfile.v0
            - --local
            - context=/workspace
            - --local
            - dockerfile=/workspace/packages/app/
            - --output
            - type=image,name=registry.dev2.fabrique.social.gouv.fr/emjpm/app:latest,push=true
            - --export-cache
            - mode=max,type=registry,ref=registry.dev2.fabrique.social.gouv.fr/emjpm/app:buildcache
            - --import-cache
            - type=registry,ref=registry.dev2.fabrique.social.gouv.fr/emjpm/app:buildcache
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - name: workspace
              readOnly: true
              mountPath: /workspace
            - name: home-docker
              mountPath: /home/user/.docker
              readOnly: false

      volumes:
        - name: workspace
          emptyDir: {}
        - name: home-docker
          emptyDir: {}