---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${K8S_NAMESPACE}-frontend${HASH_BRANCH_NAME}
  labels:
    app: ${K8S_NAMESPACE}-frontend${HASH_BRANCH_NAME}
    branch: ${BRANCH_NAME}
    commit: ${COMMIT}
    job: "${JOB_ID}"
    tag: "${COMMIT_TAG}"
spec:
  rules:
  - host: ${FRONTEND_HOST}
    http:
      paths:
      - path: /
        backend:
          serviceName: ${K8S_NAMESPACE}-frontend${HASH_BRANCH_NAME}
          servicePort: ${PORT}
