.k8s-deploy-metabase:
  extends: .base_docker_helm_image_stage
  script:
    - source ./.gitlab-ci/env.sh
    - kubectl config set-context --current --namespace=${K8S_NAMESPACE}
    #
    #
    - export POSTGRESQL_USER=metabase
    - export POSTGRESQL_PASSWORD=$(kubectl get secret emjpm-secret -o jsonpath='{.data.POSTGRES_METABASE_PASSWORD}' | base64 --decode)
    #
    - envsubst < ./.k8s/metabase/values.yaml > ./values.yaml
    #
    - helm init --client-only

    - curl -L https://github.com/SocialGouv/helm-charts/releases/download/v2.11.0/helm-just-linux-2.11.0.tgz | tar -C $(helm home) -xzv
    - helm repo add socialgouv https://github.com/SocialGouv/helm-charts/releases/download/v2.11.0

    - helm just fetch "stable/metabase#0.9.4"
    - helm just render metabase metabase --values ./values.yaml
    - helm just apply metabase
