.k8s-deploy-metabase:
  extends: .base_docker_helm_image_stage
  script:
    - source ./.gitlab-ci/env.sh
    - kubectl config set-context --current --namespace=${K8S_NAMESPACE}
    #
    #
    - export POSTGRESQL_USER=metabase
    - export POSTGRESQL_PASSWORD=$(kubectl get secret emjpm-secret -o jsonpath='{.data.POSTGRES_METABASE_PASSWORD}' | base64 --decode)
    #
    - envsubst < ./.k8s/metabase/values.yaml > ./values.yaml
    #
    - helm init --client-only
    - helm upgrade --install metabase --wait -f ./values.yaml stable/metabase --namespace ${K8S_NAMESPACE}
