#!/usr/bin/env bash
cd packages/hasura

if nc -z localhost 9695; then
  echo "hasura console already running on port 9695"
  echo "you can go to http://localhost:9695"
  exit 0
fi

echo "running hasura console"
while ! hasura console 2>/dev/null; do
  sleep 2
done