#!/usr/bin/env bash
cd packages/hasura

if !nc -z localhost 9695; then
  echo "running hasura console"
  while ! hasura console --no-browser 2>/dev/null; do
    sleep 2
  done
fi

echo "hasura console at http://localhost:9695"
