#!/bin/sh

export PGUSER=emjpm
export PGPASSWORD=test
DB=emjpm
NEW_OWNER=emjpm
DUMP_FILE=${1:-"db-seed/devdb.dump"}

cat <<EOF | psql -h localhost -p 5434 -U $PGUSER postgres
SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE pid <> pg_backend_pid() AND datname = '$DB';
DROP DATABASE IF EXISTS $DB;
CREATE DATABASE $DB WITH OWNER = $NEW_OWNER;
EOF

pg_restore -h localhost -p 5434 --if-exists --clean --no-owner --no-acl -e -Fc -d $DB $DUMP_FILE

cat <<EOF | psql -h localhost -p 5434 -U $PGUSER
DELETE FROM hdb_catalog.event_invocation_logs;
DELETE FROM hdb_catalog.event_log;
DELETE FROM hdb_catalog.event_triggers;
DELETE FROM hdb_catalog.remote_schemas;
EOF
