-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."magistrat" add column "share_email" boolean
--  not null default 'false';
