
Launch e2e tests:
  stage: Notify Finished Deployment
  image: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/curl:1.15.0
  when: manual
  except:
    variables:
      - $E2E_TEST
  script:
    - curl
        --request POST
        --form "token=${CI_JOB_TOKEN}"
        --form "ref=${CI_COMMIT_REF_NAME}"
        --form "variables[E2E_TEST]=true"
        https://gitlab.factory.social.gouv.fr/api/v4/projects/51/trigger/pipeline

#
#
#

E2E Test @optional/e2e.runner.puppetteer:
  stage: Code Quality
  image: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/puppetteer:0.28.0
  variables:
    CODECEPT_BASEURL: "http://master.code-du-travail-numerique.dev.factory.social.gouv.fr"
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - optional/e2e/puppetteer/output
  only:
    variables:
      - $E2E_TEST
  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - optional/e2e/.runners/puppetteer/node_modules
      - $CI_PROJECT_DIR/.yarn
  before_script:
    - cd ./optional/e2e/.runners/puppetteer
  script:
    - yarn config set cache-folder $CI_PROJECT_DIR/.yarn
    - yarn --frozen-lockfile
    - ls
    - yarn test

