image:
  repository: registry.gitlab.factory.social.gouv.fr/socialgouv/emjpm/graphql-server
  tag: latest

deployment:
  resources:
    limits:
      cpu: 25m
      memory: 512Mi
    requests:
      cpu: 1m
      memory: 256Mi

  livenessProbe:
    path: /health-check
  readinessProbe:
    path: /health-check

  env:
    - name: HASURA_GRAPHQL_ADMIN_SECRET
      valueFrom:
        secretKeyRef:
          name: emjpm-secret
          key: HASURA_GRAPHQL_ADMIN_SECRET
    - name: HASURA_GRAPHQL_URI
      value: "http://${HASURA_SRV_HOST}/v1/graphql"
    - name: PORT
      value: "80"
    - name: NODE_ENV
      value: "production"
    - name: SENTRY_PUBLIC_DSN
      valueFrom:
        secretKeyRef:
          name: emjpm-secret
          key: SENTRY_PUBLIC_DSN
