-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."geolocalisation_code_postal" add column "departement_code" text
--  null;
