#!/bin/bash

#!/bin/bash
set -e

POSTGRES_EMJPM_USER=${POSTGRES_EMJPM_USER:="emjpm"}
POSTGRES_EMJPM_PASSWORD=${POSTGRES_EMJPM_PASSWORD:="test"}
POSTGRES_METABASE_USER=${POSTGRES_METABASE_USER:="metabase"}
POSTGRES_METABASE_PASSWORD=${POSTGRES_METABASE_PASSWORD:="metabasePassword"}
POSTGRES_HASURA_USER=${POSTGRES_HASURA_USER:="hasura"}
POSTGRES_HASURA_PASSWORD=${POSTGRES_HASURA_PASSWORD:="hasuraPassword"}

EMJPM_DB=emjpm_${BRANCH_HASH}
METABASE_DB=metabase_${BRANCH_HASH}

if psql -lqt | cut -d \| -f 1 | grep -qw ${EMJPM_DB}; then
  exit 0;
else
psql -v ON_ERROR_STOP=1 postgres  <<-EOSQL
  CREATE DATABASE ${EMJPM_DB};
  \c ${EMJPM_DB}

  CREATE EXTENSION IF NOT EXISTS pgcrypto;
  CREATE SCHEMA IF NOT EXISTS hdb_catalog;
  CREATE SCHEMA IF NOT EXISTS hdb_views;

  -- EMJPM
  ALTER SCHEMA public OWNER TO ${POSTGRES_EMJPM_USER};
  GRANT ALL PRIVILEGES ON DATABASE ${EMJPM_DB} TO ${POSTGRES_EMJPM_USER};

  -- METABASE
  GRANT CONNECT ON DATABASE ${EMJPM_DB} TO ${POSTGRES_METABASE_USER};
  GRANT USAGE ON SCHEMA public TO ${POSTGRES_METABASE_USER};
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${POSTGRES_METABASE_USER};
  GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${POSTGRES_METABASE_USER};

   -- HASURA
  GRANT ALL PRIVILEGES ON DATABASE ${EMJPM_DB} TO ${POSTGRES_HASURA_USER};
  ALTER SCHEMA hdb_catalog OWNER TO ${POSTGRES_HASURA_USER};
  ALTER SCHEMA hdb_views OWNER TO ${POSTGRES_HASURA_USER};
  GRANT SELECT ON ALL TABLES IN SCHEMA information_schema TO ${POSTGRES_HASURA_USER};
  GRANT SELECT ON ALL TABLES IN SCHEMA pg_catalog TO ${POSTGRES_HASURA_USER};

  GRANT USAGE ON SCHEMA public TO ${POSTGRES_HASURA_USER};
  GRANT ALL ON ALL TABLES IN SCHEMA public TO ${POSTGRES_HASURA_USER};
  GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO ${POSTGRES_HASURA_USER};

  GRANT USAGE ON SCHEMA hdb_views TO ${POSTGRES_EMJPM_USER};
  GRANT ALL ON ALL TABLES IN SCHEMA hdb_views TO ${POSTGRES_EMJPM_USER};
  GRANT ALL ON ALL SEQUENCES IN SCHEMA hdb_views TO ${POSTGRES_EMJPM_USER};

  GRANT USAGE ON SCHEMA hdb_catalog TO ${POSTGRES_EMJPM_USER};
  GRANT ALL ON ALL TABLES IN SCHEMA hdb_catalog TO ${POSTGRES_EMJPM_USER};
  GRANT ALL ON ALL SEQUENCES IN SCHEMA hdb_catalog TO ${POSTGRES_EMJPM_USER};

  CREATE DATABASE ${METABASE_DB};
  \c ${METABASE_DB}
  GRANT ALL PRIVILEGES ON DATABASE ${METABASE_DB} TO ${POSTGRES_METABASE_USER};

EOSQL

fi
