#!/bin/bash

#!/bin/bash
set -e

POSTGRES_EMJPM_USER=emjpm

EMJPM_DB=${POSTGRES_DATABASE_EMJPM}

if psql -lqt | cut -d \| -f 1 | grep -qw ${EMJPM_DB}; then
  exit 0;
else
psql -v ON_ERROR_STOP=1 postgres  <<-EOSQL
  CREATE DATABASE ${EMJPM_DB};
  \c ${EMJPM_DB}

  CREATE EXTENSION IF NOT EXISTS pgcrypto;

 -- EMJPM
  GRANT CONNECT ON DATABASE ${EMJPM_DB} TO ${POSTGRES_EMJPM_USER};
  GRANT ALL PRIVILEGES ON DATABASE ${EMJPM_DB} TO ${POSTGRES_EMJPM_USER};

EOSQL

fi
