#!/bin/bash

#!/bin/bash
set -e

POSTGRES_HASURA_USER=hasura

EMJPM_DB=${POSTGRES_DATABASE_EMJPM}

if psql -lqt | cut -d \| -f 1 | grep -qw ${EMJPM_DB}; then
  exit 0;
else
psql -v ON_ERROR_STOP=1 postgres  <<-EOSQL
  CREATE DATABASE ${EMJPM_DB};
  \c ${EMJPM_DB}

  CREATE EXTENSION IF NOT EXISTS pgcrypto;

   -- HASURA
  GRANT ALL PRIVILEGES ON DATABASE ${EMJPM_DB} TO ${POSTGRES_HASURA_USER};
  GRANT SELECT ON ALL TABLES IN SCHEMA information_schema TO ${POSTGRES_HASURA_USER};
  GRANT SELECT ON ALL TABLES IN SCHEMA pg_catalog TO ${POSTGRES_HASURA_USER};

  GRANT USAGE ON SCHEMA public TO ${POSTGRES_HASURA_USER};
  GRANT ALL ON ALL TABLES IN SCHEMA public TO ${POSTGRES_HASURA_USER};
  GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO ${POSTGRES_HASURA_USER};
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES  ON TABLES TO ${POSTGRES_HASURA_USER};
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES  ON SEQUENCES TO ${POSTGRES_HASURA_USER};

EOSQL

fi
